/**
 * The course-book lesson sequences. Two books, ~120 lessons each, walked in
 * order — so the girls can always see exactly which lesson they are on.
 *
 * Each lesson is [title, skillId, difficulty]. Difficulty (0-1) feeds the same
 * question generators the rest of the app uses, so a lesson early in Math 1 and
 * a lesson late in Math 2 can share a skill but feel completely different.
 */

import type { CourseBookId } from "../../types";

export type LessonRow = [title: string, skill: string, d: number, review?: string[]];

export interface CourseUnit {
  title: string;
  emoji: string;
  rows: LessonRow[];
}

export interface CourseLesson {
  n: number;
  title: string;
  skill: string;
  d: number;
  review: string[];
  unit: number;
  unitTitle: string;
  unitEmoji: string;
}

export interface CourseBook {
  id: CourseBookId;
  title: string;
  subtitle: string;
  emoji: string;
  color: string;
  soft: string;
  units: CourseUnit[];
}

const MATH1: CourseBook = {
  id: "math1",
  title: "Math 1",
  subtitle: "Numbers, adding, subtracting & the world around us",
  emoji: "1️⃣",
  color: "#f97316",
  soft: "#fff7ed",
  units: [
    {
      title: "Numbers to 10",
      emoji: "🔢",
      rows: [
        ["Counting to 5", "count10", 0.1],
        ["Writing Numbers 1–5", "count10", 0.15],
        ["Counting to 10", "count10", 0.2],
        ["Writing Numbers 6–10", "count10", 0.25],
        ["The Number Line", "countSeq", 0.15],
        ["What Comes Next?", "countSeq", 0.2],
        ["Counting Backwards", "countBack", 0.2],
        ["More or Less", "compare", 0.15],
        ["Comparing Groups", "compare", 0.2],
        ["Equal Groups", "compare", 0.25],
        ["First, Second, Third", "ordinal", 0.2],
        ["Unit 1 Review", "count10", 0.3, ["countSeq", "compare", "ordinal"]],
      ],
    },
    {
      title: "Adding to 10",
      emoji: "➕",
      rows: [
        ["Putting Groups Together", "add5", 0.15],
        ["Adding 1", "add5", 0.15],
        ["Adding 2", "add5", 0.2],
        ["Adding to 5", "add5", 0.25],
        ["Number Bonds to 5", "numberBond", 0.2],
        ["Order Doesn't Matter", "add5", 0.3],
        ["Adding 0", "add5", 0.2],
        ["Doubles to 10", "doubles", 0.2],
        ["Number Bonds to 10", "numberBond", 0.35],
        ["Making 10", "numberBond", 0.4],
        ["Adding to 10", "add5", 0.4],
        ["Near Doubles", "doubles", 0.35],
        ["Addition Story Problems", "storyProblem", 0.2],
        ["Unit 2 Review", "numberBond", 0.4, ["add5", "doubles"]],
      ],
    },
    {
      title: "Subtracting to 10",
      emoji: "➖",
      rows: [
        ["Taking Away", "addsub20", 0.15],
        ["Subtracting 1", "addsub20", 0.15],
        ["Subtracting 2", "addsub20", 0.2],
        ["Subtracting from 5", "addsub20", 0.2],
        ["Subtracting 0 and All", "addsub20", 0.2],
        ["Subtracting from 10", "addsub20", 0.3],
        ["Missing Parts", "missing", 0.2],
        ["Fact Families to 10", "factFamily", 0.25],
        ["Add or Subtract?", "storyProblem", 0.3],
        ["Subtraction Story Problems", "storyProblem", 0.3],
        ["Fact Family Practice", "factFamily", 0.35],
        ["Unit 3 Review", "factFamily", 0.4, ["addsub20", "missing"]],
      ],
    },
    {
      title: "Shapes & Patterns",
      emoji: "🔷",
      rows: [
        ["Circles, Squares, Triangles", "shapes", 0.15],
        ["Rectangles and More", "shapes", 0.25],
        ["Sides and Corners", "sidesVertices", 0.2],
        ["Solid Shapes", "shape3d", 0.2],
        ["Shapes All Around Us", "shape3d", 0.3],
        ["Symmetry", "symmetry", 0.2],
        ["Shape Patterns", "pattern", 0.2],
        ["Color and Size Patterns", "pattern", 0.25],
        ["Number Patterns", "pattern", 0.35],
        ["Unit 4 Review", "shapes", 0.35, ["sidesVertices", "pattern"]],
      ],
    },
    {
      title: "Teen Numbers & Place Value",
      emoji: "📦",
      rows: [
        ["Ten and Some More", "teenPlace", 0.2],
        ["Teen Numbers 11–15", "teenPlace", 0.25],
        ["Teen Numbers 16–20", "teenPlace", 0.3],
        ["Tens and Ones", "tensones", 0.2],
        ["Counting by Tens", "skip", 0.2],
        ["Counting to 50", "count100", 0.3],
        ["Counting to 100", "count100", 0.4],
        ["The Hundred Chart", "count100", 0.45],
        ["10 More, 10 Less", "tenMoreLess", 0.3],
        ["Comparing 2-Digit Numbers", "compare", 0.4],
        ["Odd and Even", "oddEven", 0.25],
        ["Unit 5 Review", "tensones", 0.4, ["teenPlace", "count100"]],
      ],
    },
    {
      title: "Adding & Subtracting to 20",
      emoji: "⚡",
      rows: [
        ["Adding Teen Numbers", "addsub20", 0.35],
        ["Counting On", "addsub20", 0.35],
        ["Make a Ten to Add", "addsub20", 0.45],
        ["Doubles to 20", "doubles", 0.45],
        ["Near Doubles to 20", "doubles", 0.5],
        ["Adding Three Numbers", "addsub20", 0.5],
        ["Counting Back to Subtract", "addsub20", 0.4],
        ["Subtracting Teen Numbers", "addsub20", 0.45],
        ["Fact Families to 20", "factFamily", 0.45],
        ["Missing Addends", "missing", 0.4],
        ["Story Problems to 20", "storyProblem", 0.4],
        ["Speed Practice: Sums to 10", "add5", 0.5],
        ["Speed Practice: Sums to 20", "addsub20", 0.55],
        ["Unit 6 Review", "addsub20", 0.5, ["factFamily", "missing"]],
      ],
    },
    {
      title: "Measurement & Time",
      emoji: "📏",
      rows: [
        ["Longer and Shorter", "measure", 0.15],
        ["Measuring with Objects", "measure", 0.25],
        ["Inches and Feet", "measure", 0.35],
        ["Heavier and Lighter", "measure", 0.3],
        ["Telling Time: O'Clock", "timeHour", 0.2],
        ["Telling Time: Half Past", "timeHour", 0.3],
        ["Days of the Week", "calendar", 0.2],
        ["Months of the Year", "calendar", 0.25],
        ["Reading a Calendar", "calendar", 0.35],
        ["Morning, Noon and Night", "timeHour", 0.3],
        ["Time Practice", "timeHour", 0.4],
        ["Unit 7 Review", "measure", 0.4, ["timeHour", "calendar"]],
      ],
    },
    {
      title: "Money & Graphs",
      emoji: "🪙",
      rows: [
        ["Pennies and Nickels", "money", 0.2],
        ["Dimes and Quarters", "money", 0.3],
        ["Counting Pennies", "coinCount", 0.25],
        ["Counting Nickels and Dimes", "coinCount", 0.35],
        ["Mixed Coins", "coinCount", 0.45],
        ["Tally Marks", "graph", 0.2],
        ["Picture Graphs", "graph", 0.3],
        ["Bar Graphs", "graph", 0.35],
        ["Graph Story Problems", "graph", 0.4],
        ["Unit 8 Review", "coinCount", 0.45, ["money", "graph"]],
      ],
    },
    {
      title: "Skip Counting & Sharing",
      emoji: "🦘",
      rows: [
        ["Skip Counting by 2s", "skip", 0.25],
        ["Skip Counting by 5s", "skip", 0.3],
        ["Skip Counting by 10s", "skip", 0.3],
        ["Equal Groups", "repeatedAdd", 0.3],
        ["Sharing Equally", "shareEqually", 0.25],
        ["Halves", "fractionName", 0.2],
        ["Fourths", "fractionName", 0.3],
        ["Thirds", "fractionName", 0.35],
        ["Comparing Fractions", "fraccomp", 0.35],
        ["Half of a Group", "fractionOfSet", 0.3],
        ["Adding Tens", "tenMoreLess", 0.4],
        ["Unit 9 Review", "skip", 0.4, ["fractionName", "shareEqually"]],
      ],
    },
    {
      title: "Putting It All Together",
      emoji: "🏆",
      rows: [
        ["Two-Digit Addition", "add2digit", 0.35],
        ["Two-Digit Subtraction", "sub2digit", 0.35],
        ["Story Problems", "storyProblem", 0.45],
        ["Choosing the Operation", "storyProblem", 0.5],
        ["Two-Step Problems", "twoStep", 0.35],
        ["Fact Fluency Challenge", "addsub20", 0.6],
        ["Place Value Challenge", "tensones", 0.5],
        ["Measurement Challenge", "measure", 0.5],
        ["Money Challenge", "coinCount", 0.5],
        ["Math 1 Celebration", "addsub20", 0.6, ["tensones", "factFamily", "coinCount"]],
      ],
    },
  ],
};

const MATH2: CourseBook = {
  id: "math2",
  title: "Math 2",
  subtitle: "Bigger numbers, regrouping, multiplication & fractions",
  emoji: "2️⃣",
  color: "#0ea5e9",
  soft: "#f0f9ff",
  units: [
    {
      title: "Review & Place Value",
      emoji: "🔁",
      rows: [
        ["Numbers to 100", "count100", 0.4],
        ["Tens and Ones Review", "tensones", 0.4],
        ["Comparing Numbers", "compare", 0.45],
        ["Odd and Even", "oddEven", 0.4],
        ["Addition Facts Review", "add5", 0.5],
        ["Subtraction Facts Review", "addsub20", 0.5],
        ["Fact Families", "factFamily", 0.5],
        ["Doubles and Near Doubles", "doubles", 0.5],
        ["Making Ten", "numberBond", 0.5],
        ["10 More, 10 Less", "tenMoreLess", 0.4],
        ["Skip Counting Review", "skip", 0.4],
        ["Unit 1 Review", "tensones", 0.5, ["factFamily", "addsub20"]],
      ],
    },
    {
      title: "Two-Digit Addition",
      emoji: "➕",
      rows: [
        ["Adding Tens", "tenMoreLess", 0.45],
        ["Adding Tens and Ones", "add2digit", 0.3],
        ["Two-Digit Plus One-Digit", "add2digit", 0.35],
        ["Two-Digit Plus Two-Digit", "add2digit", 0.45],
        ["Breaking Numbers Apart", "add2digit", 0.5],
        ["Regrouping Ones into Tens", "add2digit", 0.55],
        ["Adding with Regrouping", "add2digit", 0.6],
        ["Regrouping Practice", "add2digit", 0.65],
        ["Adding Three Numbers", "addsub100", 0.6],
        ["Estimating Sums", "round", 0.4],
        ["Addition Story Problems", "storyProblem", 0.5],
        ["Checking Your Work", "add2digit", 0.6],
        ["Addition Speed Practice", "addsub100", 0.6],
        ["Unit 2 Review", "add2digit", 0.6, ["addsub100", "round"]],
      ],
    },
    {
      title: "Two-Digit Subtraction",
      emoji: "➖",
      rows: [
        ["Subtracting Tens", "tenMoreLess", 0.5],
        ["Two-Digit Minus One-Digit", "sub2digit", 0.3],
        ["Two-Digit Minus Two-Digit", "sub2digit", 0.45],
        ["Breaking Apart to Subtract", "sub2digit", 0.5],
        ["Regrouping a Ten", "sub2digit", 0.55],
        ["Subtracting with Regrouping", "sub2digit", 0.6],
        ["Regrouping Practice", "sub2digit", 0.65],
        ["Subtracting Across Zero", "sub2digit", 0.7],
        ["Checking with Addition", "factFamily", 0.55],
        ["Estimating Differences", "round", 0.45],
        ["Subtraction Story Problems", "storyProblem", 0.55],
        ["How Many More?", "storyProblem", 0.6],
        ["Subtraction Speed Practice", "addsub100", 0.65],
        ["Unit 3 Review", "sub2digit", 0.65, ["addsub100", "storyProblem"]],
      ],
    },
    {
      title: "Numbers to 1,000",
      emoji: "💯",
      rows: [
        ["Counting by Hundreds", "place100", 0.3],
        ["Hundreds, Tens and Ones", "place100", 0.4],
        ["Reading Three-Digit Numbers", "place100", 0.45],
        ["Expanded Form", "place100", 0.5],
        ["Comparing Three-Digit Numbers", "compare", 0.55],
        ["Ordering Numbers", "compare", 0.6],
        ["100 More, 100 Less", "place100", 0.55],
        ["Rounding to the Nearest Ten", "round", 0.45],
        ["Rounding to the Nearest Hundred", "round", 0.6],
        ["Adding Three-Digit Numbers", "addsub100", 0.6],
        ["Subtracting Three-Digit Numbers", "addsub100", 0.65],
        ["Unit 4 Review", "place100", 0.6, ["round", "compare"]],
      ],
    },
    {
      title: "Time",
      emoji: "🕐",
      rows: [
        ["Telling Time to the Hour", "timeHour", 0.35],
        ["Telling Time to the Half Hour", "timeHour", 0.45],
        ["Counting by Fives on the Clock", "timeFiveMin", 0.35],
        ["Telling Time to Five Minutes", "timeFiveMin", 0.5],
        ["Quarter Past and Quarter To", "timeFiveMin", 0.55],
        ["A.M. and P.M.", "timeHour", 0.5],
        ["Elapsed Time in Hours", "elapsed", 0.35],
        ["Elapsed Time in Minutes", "elapsed", 0.55],
        ["Calendars and Schedules", "calendar", 0.45],
        ["Unit 5 Review", "timeFiveMin", 0.55, ["elapsed", "calendar"]],
      ],
    },
    {
      title: "Money",
      emoji: "💵",
      rows: [
        ["Coin Review", "money", 0.4],
        ["Counting Coins", "coinCount", 0.45],
        ["Counting Mixed Coins", "coinCount", 0.55],
        ["Dollars and Cents", "coinCount", 0.6],
        ["Writing Money Amounts", "coinCount", 0.6],
        ["Comparing Money", "compare", 0.5],
        ["Adding Money", "addsub100", 0.55],
        ["Making Change", "makeChange", 0.4],
        ["Making Change Practice", "makeChange", 0.55],
        ["Money Story Problems", "storyProblem", 0.55],
        ["Shopping Challenge", "makeChange", 0.6],
        ["Unit 6 Review", "coinCount", 0.6, ["makeChange", "money"]],
      ],
    },
    {
      title: "Multiplication",
      emoji: "✖️",
      rows: [
        ["Equal Groups", "repeatedAdd", 0.35],
        ["Repeated Addition", "repeatedAdd", 0.45],
        ["Skip Counting by 2s and 5s", "skip", 0.45],
        ["Skip Counting by 3s and 4s", "skip", 0.55],
        ["What Is Multiplication?", "mult", 0.2],
        ["Arrays", "arrays", 0.3],
        ["Multiplying by 2", "mult", 0.3],
        ["Multiplying by 5", "mult", 0.35],
        ["Multiplying by 10", "mult", 0.35],
        ["Multiplying by 3", "mult", 0.45],
        ["Multiplying by 4", "mult", 0.5],
        ["Order Doesn't Matter", "arrays", 0.5],
        ["Multiplication Speed Practice", "mult", 0.6],
        ["Unit 7 Review", "mult", 0.55, ["arrays", "repeatedAdd"]],
      ],
    },
    {
      title: "Division & Fractions",
      emoji: "🍕",
      rows: [
        ["Sharing Equally", "shareEqually", 0.35],
        ["Making Equal Groups", "shareEqually", 0.5],
        ["What Is Division?", "div", 0.25],
        ["Dividing by 2", "div", 0.3],
        ["Dividing by 5 and 10", "div", 0.45],
        ["Multiplication and Division Families", "factFamily", 0.6],
        ["Halves, Thirds and Fourths", "fractionName", 0.4],
        ["Naming Fractions", "fractionName", 0.55],
        ["Comparing Fractions", "fraccomp", 0.5],
        ["Equal Fractions", "fraccomp", 0.6],
        ["Fractions of a Group", "fractionOfSet", 0.5],
        ["Unit 8 Review", "div", 0.55, ["fractionName", "shareEqually"]],
      ],
    },
    {
      title: "Measurement & Geometry",
      emoji: "📐",
      rows: [
        ["Measuring in Inches", "measure", 0.4],
        ["Inches, Feet and Yards", "measure", 0.55],
        ["Centimeters and Meters", "measure", 0.6],
        ["Estimating Length", "measure", 0.5],
        ["Perimeter", "perim", 0.35],
        ["Area", "perim", 0.5],
        ["Flat Shapes Review", "shapes", 0.45],
        ["Sides, Corners and Angles", "sidesVertices", 0.45],
        ["Solid Shapes", "shape3d", 0.45],
        ["Symmetry", "symmetry", 0.4],
        ["Shape Patterns", "pattern", 0.5],
        ["Unit 9 Review", "perim", 0.55, ["measure", "shapes"]],
      ],
    },
    {
      title: "Problem Solving",
      emoji: "🏆",
      rows: [
        ["Reading Graphs", "graph", 0.45],
        ["Bar Graphs and Line Plots", "graph", 0.55],
        ["One-Step Story Problems", "storyProblem", 0.6],
        ["Two-Step Story Problems", "twoStep", 0.45],
        ["Choosing the Operation", "twoStep", 0.6],
        ["Multi-Step Challenge", "twoStep", 0.7],
        ["Fact Fluency Challenge", "mult", 0.7],
        ["Math 2 Celebration", "addsub100", 0.7, ["mult", "place100", "storyProblem"]],
      ],
    },
  ],
};


const MATH3: CourseBook = {
  id: "math3",
  title: "Math 3",
  subtitle: "Multiplication, division, fractions & measurement",
  emoji: "3️⃣",
  color: "#8b5cf6",
  soft: "#f5f3ff",
  units: [
    { title: "Review & Place Value", emoji: "🔁", rows: [
      ["Numbers to 1,000", "place100", 0.4],
      ["Hundreds, Tens and Ones", "place100", 0.45],
      ["Comparing Large Numbers", "compare", 0.55],
      ["Rounding to Tens", "round", 0.5],
      ["Rounding to Hundreds", "roundHundred", 0.4],
      ["Odd and Even Review", "oddEven", 0.45],
      ["Skip Counting Review", "skip", 0.5],
      ["Addition Facts Review", "addsub20", 0.55],
      ["Subtraction Facts Review", "addsub20", 0.6],
      ["Fact Families", "factFamily", 0.55],
      ["10 More, 100 More", "place100", 0.5],
      ["Unit 1 Review", "place100", 0.55, ["round", "compare"]],
    ]},
    { title: "Adding & Subtracting to 1,000", emoji: "➕", rows: [
      ["Adding Hundreds", "add3digit", 0.25],
      ["Three-Digit Addition", "add3digit", 0.4],
      ["Addition with Regrouping", "add3digit", 0.55],
      ["Regrouping Twice", "add3digit", 0.65],
      ["Estimating Sums", "roundHundred", 0.5],
      ["Subtracting Hundreds", "sub3digit", 0.25],
      ["Three-Digit Subtraction", "sub3digit", 0.4],
      ["Subtraction with Regrouping", "sub3digit", 0.55],
      ["Subtracting Across Zeros", "sub3digit", 0.7],
      ["Checking with Addition", "factFamily", 0.6],
      ["Story Problems", "storyProblem", 0.5],
      ["Unit 2 Review", "add3digit", 0.6, ["sub3digit", "roundHundred"]],
    ]},
    { title: "Understanding Multiplication", emoji: "✖️", rows: [
      ["Equal Groups", "repeatedAdd", 0.35],
      ["Repeated Addition", "repeatedAdd", 0.45],
      ["What Multiplication Means", "mult", 0.2],
      ["Arrays", "arrays", 0.3],
      ["Order Doesn't Matter", "arrays", 0.45],
      ["Multiplying by 2", "mult", 0.25],
      ["Multiplying by 5", "mult", 0.3],
      ["Multiplying by 10", "multBy10", 0.2],
      ["Multiplying by 100", "multBy10", 0.55],
      ["Multiplying by 1 and 0", "mult", 0.3],
      ["Rule Machines", "functionTable", 0.3],
      ["Unit 3 Review", "mult", 0.45, ["arrays", "repeatedAdd"]],
    ]},
    { title: "Multiplication Facts", emoji: "⚡", rows: [
      ["Multiplying by 3", "mult", 0.4],
      ["Multiplying by 4", "mult", 0.45],
      ["Multiplying by 6", "mult", 0.55],
      ["Multiplying by 7", "mult", 0.6],
      ["Multiplying by 8", "mult", 0.65],
      ["Multiplying by 9", "mult", 0.65],
      ["Multiplying by 11 and 12", "mult", 0.7],
      ["Fact Practice: Mixed", "mult", 0.6],
      ["Speed Practice", "mult", 0.7],
      ["Multiplication Story Problems", "storyProblem", 0.55],
      ["Two-Step Problems", "twoStep", 0.45],
      ["Unit 4 Review", "mult", 0.7, ["functionTable", "storyProblem"]],
    ]},
    { title: "Division", emoji: "➗", rows: [
      ["Sharing Equally", "shareEqually", 0.4],
      ["What Division Means", "div", 0.25],
      ["Dividing by 2 and 5", "div", 0.35],
      ["Dividing by 3 and 4", "div", 0.45],
      ["Dividing by 10", "div", 0.4],
      ["Multiplication & Division Families", "factFamily", 0.6],
      ["Dividing by 6 and 7", "div", 0.6],
      ["Dividing by 8 and 9", "div", 0.65],
      ["Remainders", "divRemainder", 0.3],
      ["Division with Remainders", "divRemainder", 0.55],
      ["Division Story Problems", "storyProblem", 0.6],
      ["Unit 5 Review", "div", 0.6, ["divRemainder", "factFamily"]],
    ]},
    { title: "Fractions", emoji: "🍕", rows: [
      ["Equal Parts", "fractionName", 0.25],
      ["Halves, Thirds, Fourths", "fractionName", 0.35],
      ["Naming Fractions", "fractionName", 0.5],
      ["Fractions on a Number Line", "fracLine", 0.35],
      ["Comparing Fractions", "fraccomp", 0.45],
      ["Same Top, Different Bottom", "fraccomp", 0.55],
      ["Equal Fractions", "equivFrac", 0.35],
      ["Finding Equal Fractions", "equivFrac", 0.55],
      ["Fractions of a Group", "fractionOfSet", 0.45],
      ["Whole Numbers as Fractions", "fracLine", 0.55],
      ["Fraction Story Problems", "storyProblem", 0.6],
      ["Unit 6 Review", "fractionName", 0.6, ["fraccomp", "equivFrac"]],
    ]},
    { title: "Measurement", emoji: "📏", rows: [
      ["Choosing the Right Unit", "unitChoice", 0.3],
      ["Measuring in Inches", "measure", 0.45],
      ["Inches, Feet and Yards", "measure", 0.55],
      ["Centimeters and Meters", "measure", 0.6],
      ["Estimating Length", "measure", 0.5],
      ["Weight: Ounces and Pounds", "unitChoice", 0.5],
      ["Liquid: Cups, Pints, Quarts", "unitChoice", 0.6],
      ["Perimeter", "perim", 0.4],
      ["Area", "perim", 0.55],
      ["Area and Perimeter Together", "areaFormula", 0.4],
      ["Measurement Story Problems", "storyProblem", 0.6],
      ["Unit 7 Review", "measure", 0.6, ["perim", "unitChoice"]],
    ]},
    { title: "Time & Money", emoji: "🕐", rows: [
      ["Time to Five Minutes", "timeFiveMin", 0.45],
      ["Time to the Minute", "timeMinute", 0.35],
      ["Reading Any Clock", "timeMinute", 0.55],
      ["A.M. and P.M.", "timeHour", 0.55],
      ["Elapsed Time", "elapsed", 0.45],
      ["Elapsed Time in Minutes", "elapsed", 0.6],
      ["Calendars", "calendar", 0.5],
      ["Counting Money", "coinCount", 0.55],
      ["Dollars and Cents", "coinCount", 0.6],
      ["Making Change", "makeChange", 0.5],
      ["Money Story Problems", "storyProblem", 0.6],
      ["Unit 8 Review", "timeMinute", 0.6, ["elapsed", "coinCount"]],
    ]},
    { title: "Geometry", emoji: "📐", rows: [
      ["Flat Shapes Review", "shapes", 0.5],
      ["Sides and Corners", "sidesVertices", 0.5],
      ["Quadrilaterals", "quadrilateral", 0.3],
      ["Squares and Rectangles", "quadrilateral", 0.5],
      ["Rhombuses and Trapezoids", "quadrilateral", 0.65],
      ["Kinds of Angles", "angleType", 0.3],
      ["Right Angles Everywhere", "angleType", 0.5],
      ["Solid Shapes", "shape3d", 0.5],
      ["Faces, Edges and Vertices", "sidesVertices", 0.6],
      ["Symmetry", "symmetry", 0.5],
      ["Shape Patterns", "pattern", 0.55],
      ["Unit 9 Review", "quadrilateral", 0.6, ["angleType", "shape3d"]],
    ]},
    { title: "Data & Problem Solving", emoji: "🏆", rows: [
      ["Tally Charts", "graph", 0.4],
      ["Picture Graphs", "graph", 0.5],
      ["Bar Graphs", "graph", 0.6],
      ["Reading Any Graph", "graph", 0.65],
      ["Number Patterns", "pattern", 0.6],
      ["Rule Machines", "functionTable", 0.55],
      ["One-Step Problems", "storyProblem", 0.6],
      ["Two-Step Problems", "twoStep", 0.55],
      ["Choosing the Operation", "twoStep", 0.65],
      ["Multi-Step Challenge", "twoStep", 0.75],
      ["Fact Fluency Challenge", "mult", 0.75],
      ["Math 3 Celebration", "div", 0.7, ["mult", "fractionName", "perim"]],
    ]},
  ],
};

const MATH4: CourseBook = {
  id: "math4",
  title: "Math 4",
  subtitle: "Big numbers, long division, fractions & decimals",
  emoji: "4️⃣",
  color: "#10b981",
  soft: "#ecfdf5",
  units: [
    { title: "Place Value to Millions", emoji: "💯", rows: [
      ["Numbers to 10,000", "place100", 0.5],
      ["Thousands and Ten Thousands", "placeMillions", 0.3],
      ["Hundred Thousands", "placeMillions", 0.5],
      ["Millions", "placeMillions", 0.65],
      ["Reading Big Numbers", "placeMillions", 0.6],
      ["Expanded Form", "place100", 0.6],
      ["Comparing Big Numbers", "compare", 0.65],
      ["Ordering Big Numbers", "compare", 0.7],
      ["Rounding to Tens and Hundreds", "roundHundred", 0.5],
      ["Rounding Big Numbers", "round", 0.7],
      ["Estimating to Check", "roundHundred", 0.65],
      ["Unit 1 Review", "placeMillions", 0.6, ["round", "compare"]],
    ]},
    { title: "Addition & Subtraction", emoji: "➕", rows: [
      ["Adding Three-Digit Numbers", "add3digit", 0.5],
      ["Adding Four-Digit Numbers", "add3digit", 0.7],
      ["Regrouping Across Places", "add3digit", 0.75],
      ["Subtracting Three-Digit Numbers", "sub3digit", 0.5],
      ["Subtracting Four-Digit Numbers", "sub3digit", 0.7],
      ["Subtracting Across Zeros", "sub3digit", 0.75],
      ["Checking with the Inverse", "factFamily", 0.65],
      ["Estimating Sums and Differences", "roundHundred", 0.6],
      ["Addition Story Problems", "storyProblem", 0.6],
      ["Subtraction Story Problems", "storyProblem", 0.65],
      ["Two-Step Problems", "twoStep", 0.55],
      ["Unit 2 Review", "add3digit", 0.7, ["sub3digit", "twoStep"]],
    ]},
    { title: "Multi-Digit Multiplication", emoji: "✖️", rows: [
      ["Multiplication Facts Review", "mult", 0.65],
      ["Multiplying by 10, 100, 1000", "multBy10", 0.6],
      ["Breaking Numbers Apart", "bigmult", 0.25],
      ["Two-Digit by One-Digit", "bigmult", 0.4],
      ["Regrouping in Multiplication", "bigmult", 0.55],
      ["Three-Digit by One-Digit", "bigmult", 0.65],
      ["Two-Digit by Two-Digit", "bigmult", 0.75],
      ["The Distributive Property", "distributive", 0.4],
      ["Estimating Products", "roundHundred", 0.6],
      ["Area Models", "arrays", 0.6],
      ["Multiplication Story Problems", "storyProblem", 0.65],
      ["Unit 3 Review", "bigmult", 0.7, ["distributive", "multBy10"]],
    ]},
    { title: "Division", emoji: "➗", rows: [
      ["Division Facts Review", "div", 0.6],
      ["Dividing by 10 and 100", "multBy10", 0.6],
      ["Remainders", "divRemainder", 0.4],
      ["Chunking to Divide", "longdiv", 0.3],
      ["Two-Digit by One-Digit", "longdiv", 0.45],
      ["Three-Digit by One-Digit", "longdiv", 0.6],
      ["Division with Remainders", "divRemainder", 0.65],
      ["Interpreting the Remainder", "divRemainder", 0.7],
      ["Checking Division", "factFamily", 0.7],
      ["Estimating Quotients", "roundHundred", 0.65],
      ["Division Story Problems", "storyProblem", 0.7],
      ["Unit 4 Review", "longdiv", 0.65, ["divRemainder", "div"]],
    ]},
    { title: "Factors & Multiples", emoji: "🔢", rows: [
      ["What Is a Factor?", "factors", 0.3],
      ["Finding All the Factors", "factors", 0.5],
      ["Factor Pairs", "factors", 0.6],
      ["What Is a Multiple?", "skip", 0.6],
      ["Finding Multiples", "skip", 0.7],
      ["Common Factors", "factors", 0.7],
      ["Common Multiples", "skip", 0.75],
      ["Prime Numbers", "primeComposite", 0.3],
      ["Composite Numbers", "primeComposite", 0.5],
      ["Prime or Composite?", "primeComposite", 0.65],
      ["Number Patterns", "pattern", 0.65],
      ["Unit 5 Review", "factors", 0.65, ["primeComposite", "skip"]],
    ]},
    { title: "Fractions", emoji: "🍕", rows: [
      ["Fractions Review", "fractionName", 0.55],
      ["Fractions on a Number Line", "fracLine", 0.5],
      ["Equal Fractions", "equivFrac", 0.5],
      ["Simplest Form", "equivFrac", 0.7],
      ["Comparing Fractions", "fraccomp", 0.6],
      ["Comparing Unlike Fractions", "fraccomp", 0.7],
      ["Adding Fractions", "fracAdd", 0.4],
      ["Subtracting Fractions", "fracSub", 0.4],
      ["Adding and Subtracting Practice", "fracAdd", 0.65],
      ["Improper Fractions", "mixedNumber", 0.4],
      ["Mixed Numbers", "mixedNumber", 0.6],
      ["Unit 6 Review", "fracAdd", 0.65, ["mixedNumber", "equivFrac"]],
    ]},
    { title: "Decimals", emoji: "🔟", rows: [
      ["Tenths", "decimalPlace", 0.25],
      ["Hundredths", "decimalPlace", 0.5],
      ["Reading Decimals", "decimalPlace", 0.6],
      ["Decimals and Fractions", "fdpConvert", 0.3],
      ["Decimals on a Number Line", "fracLine", 0.6],
      ["Comparing Decimals", "decimalCompare", 0.4],
      ["Ordering Decimals", "decimalCompare", 0.6],
      ["Adding Decimals", "decimals", 0.45],
      ["Subtracting Decimals", "decimals", 0.6],
      ["Decimals and Money", "coinCount", 0.65],
      ["Decimal Story Problems", "storyProblem", 0.65],
      ["Unit 7 Review", "decimalPlace", 0.65, ["decimalCompare", "fdpConvert"]],
    ]},
    { title: "Measurement & Conversion", emoji: "📏", rows: [
      ["Choosing Units", "unitChoice", 0.5],
      ["Inches, Feet, Yards, Miles", "convertUnits", 0.3],
      ["Converting Length", "convertUnits", 0.5],
      ["Metric Length", "convertUnits", 0.6],
      ["Weight and Mass", "convertUnits", 0.65],
      ["Liquid Volume", "unitChoice", 0.65],
      ["Converting Time", "convertUnits", 0.6],
      ["Perimeter Formula", "areaFormula", 0.4],
      ["Area Formula", "areaFormula", 0.55],
      ["Area of Combined Shapes", "areaFormula", 0.75],
      ["Measurement Story Problems", "storyProblem", 0.7],
      ["Unit 8 Review", "convertUnits", 0.65, ["areaFormula", "unitChoice"]],
    ]},
    { title: "Geometry & Angles", emoji: "📐", rows: [
      ["Points, Lines and Rays", "sidesVertices", 0.5],
      ["Parallel and Perpendicular", "quadrilateral", 0.6],
      ["Kinds of Angles", "angleType", 0.4],
      ["Measuring Angles", "angleType", 0.6],
      ["Angles in Shapes", "angleType", 0.7],
      ["Quadrilaterals", "quadrilateral", 0.55],
      ["Triangles", "sidesVertices", 0.6],
      ["Solid Shapes", "shape3d", 0.6],
      ["Lines of Symmetry", "symmetry", 0.6],
      ["Shape Patterns", "pattern", 0.7],
      ["Geometry Challenge", "quadrilateral", 0.75],
      ["Unit 9 Review", "angleType", 0.65, ["quadrilateral", "symmetry"]],
    ]},
    { title: "Data & Problem Solving", emoji: "🏆", rows: [
      ["Bar Graphs", "graph", 0.6],
      ["Line Plots", "graph", 0.7],
      ["Reading Data Tables", "graph", 0.65],
      ["Rule Machines", "functionTable", 0.65],
      ["Number Patterns", "pattern", 0.7],
      ["One-Step Problems", "storyProblem", 0.7],
      ["Two-Step Problems", "twoStep", 0.6],
      ["Multi-Step Problems", "twoStep", 0.75],
      ["Choosing the Operation", "twoStep", 0.7],
      ["Estimating to Check", "roundHundred", 0.7],
      ["Fact Fluency Challenge", "mult", 0.8],
      ["Math 4 Celebration", "longdiv", 0.7, ["bigmult", "fracAdd", "decimalPlace"]],
    ]},
  ],
};

const MATH5: CourseBook = {
  id: "math5",
  title: "Math 5",
  subtitle: "Fractions, decimals, percents, geometry & algebra",
  emoji: "5️⃣",
  color: "#f43f5e",
  soft: "#fff1f2",
  units: [
    { title: "Whole Number Review", emoji: "🔁", rows: [
      ["Place Value to Millions", "placeMillions", 0.6],
      ["Rounding and Estimating", "round", 0.7],
      ["Adding and Subtracting", "add3digit", 0.75],
      ["Multiplication Facts", "mult", 0.75],
      ["Multi-Digit Multiplication", "bigmult", 0.7],
      ["Long Division", "longdiv", 0.6],
      ["Division with Remainders", "divRemainder", 0.7],
      ["Factors and Multiples", "factors", 0.7],
      ["Prime and Composite", "primeComposite", 0.7],
      ["Order of Operations", "orderops", 0.3],
      ["Order of Operations with Brackets", "orderops", 0.6],
      ["Unit 1 Review", "orderops", 0.65, ["bigmult", "longdiv"]],
    ]},
    { title: "Adding & Subtracting Fractions", emoji: "🍕", rows: [
      ["Fractions Review", "fractionName", 0.6],
      ["Equal Fractions", "equivFrac", 0.6],
      ["Simplest Form", "equivFrac", 0.75],
      ["Comparing Fractions", "fraccomp", 0.7],
      ["Improper Fractions", "mixedNumber", 0.5],
      ["Mixed Numbers", "mixedNumber", 0.7],
      ["Adding Like Fractions", "fracAdd", 0.5],
      ["Subtracting Like Fractions", "fracSub", 0.5],
      ["Common Denominators", "equivFrac", 0.8],
      ["Adding Unlike Fractions", "fracAdd", 0.75],
      ["Subtracting Unlike Fractions", "fracSub", 0.75],
      ["Unit 2 Review", "fracAdd", 0.75, ["fracSub", "mixedNumber"]],
    ]},
    { title: "Multiplying & Dividing Fractions", emoji: "✖️", rows: [
      ["A Part of a Part", "fracMult", 0.25],
      ["Fraction Times Whole Number", "fracMult", 0.4],
      ["Fraction Times Fraction", "fracMult", 0.55],
      ["Multiplying Mixed Numbers", "fracMult", 0.75],
      ["Simplifying as You Go", "equivFrac", 0.8],
      ["Dividing a Fraction", "fracDiv", 0.3],
      ["Fraction Divided by Whole", "fracDiv", 0.5],
      ["Whole Divided by Fraction", "fracDiv", 0.7],
      ["Fraction Story Problems", "storyProblem", 0.7],
      ["Fractions of a Group", "fractionOfSet", 0.7],
      ["Fraction Challenge", "fracMult", 0.8],
      ["Unit 3 Review", "fracMult", 0.7, ["fracDiv", "fractionOfSet"]],
    ]},
    { title: "Decimals", emoji: "🔟", rows: [
      ["Decimal Place Value", "decimalPlace", 0.6],
      ["Thousandths", "decimalPlace", 0.75],
      ["Comparing Decimals", "decimalCompare", 0.6],
      ["Rounding Decimals", "round", 0.75],
      ["Adding Decimals", "decimals", 0.6],
      ["Subtracting Decimals", "decimals", 0.7],
      ["Multiplying Decimals", "decimalMult", 0.35],
      ["Decimal Times Decimal", "decimalMult", 0.6],
      ["Dividing Decimals", "decimalDiv", 0.35],
      ["Dividing by a Decimal", "decimalDiv", 0.65],
      ["Decimal Story Problems", "storyProblem", 0.7],
      ["Unit 4 Review", "decimalMult", 0.65, ["decimalDiv", "decimalPlace"]],
    ]},
    { title: "Percents", emoji: "💯", rows: [
      ["What Percent Means", "percent", 0.25],
      ["Percents on a Grid", "percent", 0.4],
      ["Percent of a Number", "percent", 0.55],
      ["Fractions to Decimals", "fdpConvert", 0.4],
      ["Decimals to Percents", "fdpConvert", 0.55],
      ["Percents to Fractions", "fdpConvert", 0.65],
      ["Converting All Three", "fdpConvert", 0.75],
      ["Common Percents", "fdpConvert", 0.6],
      ["Percents and Money", "percent", 0.7],
      ["Discounts and Tips", "percent", 0.8],
      ["Percent Story Problems", "storyProblem", 0.75],
      ["Unit 5 Review", "percent", 0.7, ["fdpConvert", "decimalPlace"]],
    ]},
    { title: "Expressions & Equations", emoji: "🧮", rows: [
      ["Order of Operations", "orderops", 0.6],
      ["The Distributive Property", "distributive", 0.35],
      ["Using the Distributive Property", "distributive", 0.6],
      ["Exponents", "exponent", 0.3],
      ["Powers of 10", "multBy10", 0.7],
      ["Square Numbers", "exponent", 0.55],
      ["Square Roots", "squareRoot", 0.35],
      ["What Is a Variable?", "algebra", 0.25],
      ["Solving x + a = b", "algebra", 0.45],
      ["Solving ax = b", "algebra", 0.65],
      ["Writing Equations from Stories", "algebra", 0.75],
      ["Unit 6 Review", "algebra", 0.65, ["exponent", "distributive"]],
    ]},
    { title: "Geometry & Angles", emoji: "📐", rows: [
      ["Kinds of Angles", "angleType", 0.5],
      ["Measuring with a Protractor", "angleType", 0.65],
      ["Angles on a Line", "angleType", 0.75],
      ["Triangles", "sidesVertices", 0.65],
      ["Quadrilaterals", "quadrilateral", 0.65],
      ["Congruent Shapes", "symmetry", 0.65],
      ["Lines of Symmetry", "symmetry", 0.7],
      ["Solid Shapes", "shape3d", 0.65],
      ["Faces, Edges and Vertices", "sidesVertices", 0.75],
      ["Parts of a Circle", "circle", 0.3],
      ["Radius and Diameter", "circle", 0.6],
      ["Unit 7 Review", "angleType", 0.7, ["circle", "quadrilateral"]],
    ]},
    { title: "Area, Volume & Circles", emoji: "📦", rows: [
      ["Perimeter", "areaFormula", 0.5],
      ["Area of Rectangles", "areaFormula", 0.6],
      ["Area of Combined Shapes", "areaFormula", 0.8],
      ["Circumference", "circle", 0.7],
      ["Area of a Circle", "circle", 0.8],
      ["What Is Volume?", "volume", 0.25],
      ["Counting Unit Cubes", "volume", 0.45],
      ["Volume Formula", "volume", 0.6],
      ["Volume of Combined Solids", "volume", 0.8],
      ["Converting Measurements", "convertUnits", 0.7],
      ["Metric Conversions", "convertUnits", 0.8],
      ["Unit 8 Review", "volume", 0.7, ["areaFormula", "circle"]],
    ]},
    { title: "Coordinates & Negatives", emoji: "🗺️", rows: [
      ["The Coordinate Plane", "coord", 0.25],
      ["Plotting Points", "coord", 0.45],
      ["Reading Coordinates", "coord", 0.6],
      ["Shapes on the Grid", "coord", 0.75],
      ["Below Zero", "negative", 0.25],
      ["Comparing Negative Numbers", "negative", 0.45],
      ["Adding Negative Numbers", "negative", 0.65],
      ["Subtracting with Negatives", "negative", 0.8],
      ["Temperature and Elevation", "negative", 0.7],
      ["Rule Machines", "functionTable", 0.75],
      ["Graphing a Rule", "coord", 0.8],
      ["Unit 9 Review", "coord", 0.7, ["negative", "functionTable"]],
    ]},
    { title: "Data, Probability & Problem Solving", emoji: "🏆", rows: [
      ["Bar Graphs and Line Plots", "graph", 0.7],
      ["Reading Data Tables", "graph", 0.75],
      ["Mean and Range", "graph", 0.8],
      ["What Is Probability?", "probability", 0.25],
      ["Probability as a Fraction", "probability", 0.5],
      ["Likely and Unlikely", "probability", 0.7],
      ["One-Step Problems", "storyProblem", 0.75],
      ["Two-Step Problems", "twoStep", 0.7],
      ["Multi-Step Problems", "twoStep", 0.8],
      ["Choosing the Operation", "twoStep", 0.8],
      ["Fact Fluency Challenge", "mult", 0.85],
      ["Math 5 Celebration", "fdpConvert", 0.8, ["fracMult", "percent", "volume"]],
    ]},
  ],
};

export const BOOKS: CourseBook[] = [MATH1, MATH2, MATH3, MATH4, MATH5];

function flatten(book: CourseBook): CourseLesson[] {
  const out: CourseLesson[] = [];
  let n = 0;
  book.units.forEach((u, ui) => {
    for (const row of u.rows) {
      n += 1;
      out.push({
        n,
        title: row[0],
        skill: row[1],
        d: row[2],
        review: row[3] ?? [],
        unit: ui + 1,
        unitTitle: u.title,
        unitEmoji: u.emoji,
      });
    }
  });
  return out;
}

export const COURSE_LESSONS: Record<CourseBookId, CourseLesson[]> = {
  math1: flatten(MATH1),
  math2: flatten(MATH2),
  math3: flatten(MATH3),
  math4: flatten(MATH4),
  math5: flatten(MATH5),
};

export const bookById = (id: CourseBookId): CourseBook => BOOKS.find((b) => b.id === id)!;
