import type { GradeDef } from "./types";

/** Grade 4: Greek and Latin roots, content-area reading. 120–170 words. */
export const GRADE_4: GradeDef = {
  id: "4",
  label: "Grade 4",
  emoji: "4️⃣",
  color: "#10b981",
  soft: "#ecfdf5",
  wcpm: { fall: 94, winter: 120, spring: 133 },
  units: [
    { title: "Word Roots", weeks: [
      ["Roots: port, dict, scrib", ["transport", "predict", "describe", "import", "dictate"], ["although", "because", "through", "consequently", "furthermore"], [
        "Many English words are built from Latin pieces that still carry their old meanings.",
        "The root port means to carry, which is why we transport goods and import food.",
        "A passport carries you across a border, and a porter carries your bags.",
        "The root dict means to say or speak.",
        "When you predict something, you are saying it before it happens.",
        "A dictator is someone whose word becomes law, and to dictate is to speak aloud for someone else to write down.",
        "The root scrib or script means to write.",
        "You describe something by writing it down in words, and a prescription is written by a doctor.",
        "Once you know a handful of roots, unfamiliar words stop looking like nonsense.",
        "You can take them apart and make a reasonable guess at the meaning.",
      ]],
      ["Roots: spect, struct, tract", ["inspect", "construct", "attract", "spectator", "subtract"], ["although", "furthermore", "consequently", "therefore", "nevertheless"], [
        "The root spect means to look, and it hides inside a surprising number of words.",
        "A spectator looks on at a game, and an inspector looks closely at a building.",
        "When something is spectacular, it is worth looking at.",
        "The root struct means to build.",
        "You construct a model, destroy a sandcastle, and study the structure of a sentence.",
        "Instructions are the pieces of information built up to guide you.",
        "The root tract means to pull or drag.",
        "A tractor pulls a plow, a magnet attracts metal, and when you subtract you pull a number away.",
        "Nevertheless, roots are not a perfect system.",
        "English borrowed words from dozens of languages, and some of them simply do not break apart.",
      ]],
      ["Greek roots", ["telescope", "biography", "photograph", "geography", "microscope"], ["although", "therefore", "furthermore", "consequently", "nevertheless"], [
        "Greek roots cluster around science and learning, because Greek scholars named so much of it.",
        "Tele means far, and scope means to look, so a telescope looks far away.",
        "Micro means small, which makes a microscope a tool for looking at small things.",
        "Bio means life and graph means writing, so a biography is a written life.",
        "Photo means light, and therefore a photograph is written with light.",
        "Geo means earth, so geography is writing about the earth and geology is the study of it.",
        "Thermo means heat, which explains the thermometer and the thermos.",
        "Furthermore, these pieces combine freely.",
        "A word nobody has ever used, like photobiology, is still readable the first time you see it.",
      ]],
    ]},
    { title: "Reading Science", weeks: [
      ["Earthquakes", ["tectonic", "fault", "seismic", "magnitude", "epicenter"], ["although", "because", "therefore", "consequently", "nevertheless"], [
        "The outer shell of the Earth is broken into enormous tectonic plates.",
        "They float on hotter rock below and grind slowly past one another.",
        "Where two plates meet, the boundary is called a fault.",
        "The rock along a fault does not slide smoothly; friction locks it in place.",
        "Stress builds for years or centuries until the rock finally gives way.",
        "That sudden release sends seismic waves outward in every direction.",
        "The point underground where the break begins is the focus, and the spot directly above it on the surface is the epicenter.",
        "Magnitude measures the energy released, and each whole number is about thirty-two times more energy than the one below it.",
        "Therefore a magnitude seven earthquake is not slightly worse than a six.",
        "It releases roughly thirty-two times as much energy.",
      ]],
      ["The human heart", ["circulation", "ventricle", "artery", "oxygen", "contract"], ["although", "because", "therefore", "furthermore", "consequently"], [
        "Your heart is a muscle about the size of your fist, and it never rests.",
        "It beats roughly one hundred thousand times a day without being told to.",
        "The heart has four chambers: two atria on top and two ventricles below.",
        "Blood returning from the body is low in oxygen and enters the right side.",
        "The right ventricle contracts and pushes that blood to the lungs.",
        "There it drops off carbon dioxide and picks up fresh oxygen.",
        "The blood returns to the left side, and the left ventricle sends it out through the largest artery in the body.",
        "Because that chamber has to reach your toes and your brain, its walls are the thickest.",
        "The whole circuit takes under a minute.",
        "Furthermore, a single drop of blood will make that trip thousands of times.",
      ]],
      ["Volcanoes", ["magma", "eruption", "pressure", "dormant", "crater"], ["although", "because", "therefore", "consequently", "nevertheless"], [
        "Deep below the surface, rock is hot enough to melt into magma.",
        "Magma is lighter than the solid rock around it, so it rises slowly.",
        "As it rises, dissolved gases come out of solution, the way bubbles appear when you open a bottle.",
        "Those gases build pressure, and pressure is what makes an eruption violent.",
        "Runny magma lets gas escape gently, producing the slow lava flows of Hawaii.",
        "Thick, sticky magma traps the gas until it explodes, as it did at Mount St. Helens.",
        "Once magma reaches the surface it is called lava.",
        "A volcano that has not erupted recently but could again is called dormant, not extinct.",
        "Nevertheless, dormant does not mean safe.",
        "Some of the most destructive eruptions in history came from mountains nobody expected to wake up.",
      ]],
    ]},
    { title: "Reading History", weeks: [
      ["The Silk Road", ["caravan", "merchant", "exchange", "route", "civilization"], ["although", "because", "therefore", "furthermore", "consequently"], [
        "The Silk Road was never a single road, and silk was only part of what moved along it.",
        "It was a web of routes connecting China to the Mediterranean, stretching four thousand miles.",
        "Very few merchants traveled the whole distance.",
        "Instead, goods changed hands dozens of times, and the price climbed at every exchange.",
        "Caravans carried silk and porcelain west, and glass, wool and horses east.",
        "Along with goods traveled something far more important: ideas.",
        "Paper, gunpowder and the printing press all moved west along these routes.",
        "Religions, mathematics and astronomy traveled in both directions.",
        "Consequently, civilizations that never met face to face still shaped one another deeply.",
        "The routes also carried disease, including the plague that reshaped Europe in the fourteenth century.",
      ]],
      ["The printing press", ["movable", "manuscript", "literacy", "revolution", "distribute"], ["although", "because", "therefore", "furthermore", "nevertheless"], [
        "Before the printing press, every book in Europe was copied by hand.",
        "A single manuscript could take a skilled scribe more than a year.",
        "Books were therefore rare, expensive, and owned mostly by churches and the wealthy.",
        "Around 1440 Johannes Gutenberg combined several existing ideas into one machine.",
        "His key contribution was movable metal type that could be rearranged and reused.",
        "A page could be set once and printed hundreds of times.",
        "Within fifty years there were presses in more than two hundred European cities.",
        "The price of a book fell sharply, and literacy began to climb.",
        "Nevertheless, the revolution was not only about cost.",
        "For the first time, two people in different countries could read exactly the same words, with no copying errors between them.",
      ]],
      ["Mapping the world", ["longitude", "latitude", "navigation", "chronometer", "accurate"], ["although", "because", "therefore", "consequently", "furthermore"], [
        "For centuries sailors could find their latitude easily but not their longitude.",
        "Latitude is how far north or south you are, and the sun and stars give it away.",
        "Longitude is how far east or west, and nothing in the sky answers that directly.",
        "The solution turned out to be a clock.",
        "If you know the exact time at a fixed place and compare it to local noon, the difference gives your longitude.",
        "The problem was that no clock could keep accurate time on a rolling, salty ship.",
        "John Harrison, a carpenter with no formal training, spent forty years solving it.",
        "His fourth chronometer lost only five seconds on a voyage to Jamaica.",
        "Consequently, navigation became a matter of arithmetic rather than guesswork.",
        "Countless lives were saved by a box of gears.",
      ]],
    ]},
    { title: "Reading Closely", weeks: [
      ["Author's purpose", ["persuade", "inform", "entertain", "evidence", "opinion"], ["although", "because", "therefore", "furthermore", "nevertheless"], [
        "Every piece of writing is trying to do something to you.",
        "Most writing aims to inform, to persuade, or to entertain, and often more than one at once.",
        "Learning to tell them apart changes how you read.",
        "A text that informs sticks mostly to facts that can be checked.",
        "A text that persuades selects its facts, and the selection is the argument.",
        "Watch for words that carry feeling rather than information.",
        "A road described as narrow is informing you; a road described as treacherous is persuading you.",
        "Neither is dishonest, but they are doing different work.",
        "Furthermore, the strongest persuasion rarely announces itself.",
        "It arrives dressed as a simple account of what happened.",
      ]],
      ["Fact and opinion", ["verify", "claim", "support", "reliable", "source"], ["although", "because", "therefore", "consequently", "nevertheless"], [
        "A fact is a claim that can be checked against the world.",
        "An opinion is a judgment, and reasonable people can hold different ones.",
        "The tricky part is that opinions often wear the clothing of facts.",
        "The sentence this is the best museum in the state sounds factual but cannot be verified.",
        "The sentence this museum had more visitors than any other last year can be.",
        "When you meet a claim, ask what would have to be true for it to be false.",
        "If you cannot imagine such evidence, you are probably looking at an opinion.",
        "Then ask where the claim came from.",
        "A reliable source names its evidence and tells you how it was gathered.",
        "Nevertheless, even careful sources make mistakes, which is why two independent sources beat one.",
      ]],
      ["Comparing accounts", ["perspective", "primary", "secondary", "witness", "interpret"], ["although", "because", "therefore", "furthermore", "consequently"], [
        "Historians distinguish between primary and secondary sources.",
        "A primary source comes from someone who was there: a letter, a photograph, a court record.",
        "A secondary source is written later by someone studying those materials.",
        "Both are useful, and both have limits.",
        "A witness saw only part of the event, from one position, through their own expectations.",
        "Two honest people at the same event will produce two different accounts.",
        "That is not evidence that one of them is lying.",
        "Historians therefore read many accounts and look for where they agree.",
        "Furthermore, they pay attention to what every account leaves out.",
        "Silence in the record often says as much as the words that survived.",
      ]],
    ]},
    { title: "Reading Geography", weeks: [
      ["Climate zones", ["latitude", "equator", "tropical", "temperate", "polar"], ["although", "because", "therefore", "consequently", "furthermore"], [
        "The Earth is tilted about twenty-three degrees on its axis, and that tilt creates the seasons.",
        "It also creates climate zones that wrap around the planet in bands.",
        "Near the equator, sunlight arrives almost straight down all year.",
        "That energy is concentrated, so tropical regions stay warm and have no real winter.",
        "Toward the poles the same sunlight strikes at a steep angle and spreads over a wider area.",
        "Consequently the energy is diluted, and polar regions stay cold even in summer.",
        "Between them lie the temperate zones, which get a genuine change of seasons.",
        "Latitude is therefore the single best predictor of a place's climate.",
        "Furthermore, elevation acts like latitude: climbing a mountain is roughly like traveling north.",
        "A tropical peak can have snow on top while bananas grow at its base.",
      ]],
      ["Natural resources", ["renewable", "extract", "reserve", "distribution", "sustainable"], ["although", "because", "therefore", "consequently", "nevertheless"], [
        "A natural resource is anything useful that comes from the Earth rather than from a factory.",
        "Some are renewable, meaning they replace themselves on a human timescale.",
        "Sunlight, wind and timber all fall into that category, although timber only if it is replanted.",
        "Others are nonrenewable, because they formed over millions of years.",
        "Coal, oil and most metals cannot be replaced once they are extracted.",
        "Resources are distributed very unevenly across the planet.",
        "Chile holds enormous copper reserves, and the Democratic Republic of the Congo holds most of the world's cobalt.",
        "That uneven distribution has shaped trade, wealth and conflict for all of recorded history.",
        "Nevertheless, a country's resources do not determine its future.",
        "Japan has almost none and built one of the largest economies on Earth.",
      ]],
      ["How cities grow", ["population", "urban", "transportation", "density", "suburb"], ["although", "because", "therefore", "consequently", "furthermore"], [
        "For most of human history, almost everybody farmed.",
        "A city could only grow as large as the surrounding farmland could feed.",
        "Two inventions broke that limit: better farming and better transportation.",
        "When fewer farmers could feed more people, the extra people moved to cities.",
        "When railways and refrigeration arrived, food could travel hundreds of miles.",
        "Consequently cities grew in a century from tens of thousands to millions.",
        "The shape of a city is mostly decided by how people get around in it.",
        "Cities built before cars are dense, because everything had to be within walking distance.",
        "Cities built after cars spread out into suburbs, because distance stopped mattering as much.",
        "Furthermore, in 2007 the world passed a quiet milestone: more people now live in cities than outside them.",
      ]],
    ]},
    { title: "Figurative Language", weeks: [
      ["Imagery", ["sensory", "describe", "atmosphere", "concrete", "abstract"], ["although", "because", "therefore", "consequently", "furthermore"], [
        "Imagery is writing that goes through the senses rather than straight to the brain.",
        "Compare two sentences: the kitchen was welcoming, and the kitchen smelled of bread and woodsmoke.",
        "The first is abstract and tells you a conclusion.",
        "The second is concrete and lets you reach the conclusion yourself.",
        "Readers trust conclusions they reach themselves far more than ones they are handed.",
        "Good imagery uses more than sight, which is the sense writers overuse.",
        "Sound, smell and texture are less expected and therefore more striking.",
        "Smell in particular is wired directly to memory in a way the other senses are not.",
        "Furthermore, a single precise detail beats three vague ones.",
        "One cracked blue teacup does more work than a long description of an old kitchen.",
      ]],
      ["Symbolism", ["represent", "symbol", "significance", "recurring", "interpret"], ["although", "because", "therefore", "consequently", "nevertheless"], [
        "A symbol is something concrete that stands for something abstract.",
        "A dove stands for peace, a crown for authority, a road for a life.",
        "Symbols only work because a group of people already agrees on them.",
        "That is why symbols do not always travel between cultures.",
        "In much of the West, white is the color of weddings; in parts of Asia, it is the color of mourning.",
        "Writers also build private symbols inside a single story.",
        "If a character's broken watch appears three times at important moments, it has become a symbol.",
        "You know because it recurs, and because it shows up when the subject is time or loss.",
        "Nevertheless, not every object means something.",
        "Sometimes a river is simply a river, and reading too much into it is its own mistake.",
      ]],
      ["Tone and mood", ["attitude", "atmosphere", "perspective", "deliberate", "formal"], ["although", "because", "therefore", "consequently", "furthermore"], [
        "Tone is the writer's attitude toward the subject; mood is how the reader is made to feel.",
        "They are related but not the same, and separating them is a useful habit.",
        "A writer can describe a terrifying event in a calm, formal tone.",
        "That gap between tone and content is often what makes the writing disturbing.",
        "Word choice carries most of the tone.",
        "A crowd can be described as a gathering, an assembly, a mob or a swarm.",
        "All four could be the same hundred people, and each word commits you to a different attitude.",
        "Sentence length matters too: short sentences feel urgent, long ones feel considered.",
        "Furthermore, what a writer leaves out shapes tone as much as what they include.",
      ]],
    ]},
    { title: "Reading About People", weeks: [
      ["Katherine Johnson", ["calculate", "trajectory", "orbit", "segregation", "precision"], ["although", "because", "therefore", "consequently", "nevertheless"], [
        "Katherine Johnson could do mathematics that almost nobody else at NASA could do.",
        "She calculated the trajectories that sent Americans into space and brought them home.",
        "She did this at a time when she was required to use separate facilities because she was Black.",
        "Her work had to be exact, because a trajectory error of a fraction of a degree means missing the Earth.",
        "When NASA first used electronic computers to plan John Glenn's orbit, Glenn did not trust them.",
        "He asked specifically for Johnson to check the machine's numbers by hand.",
        "He said that if she agreed with the computer, he was ready to go.",
        "She worked the problem for a day and a half and confirmed it.",
        "Nevertheless, her name was not widely known for another fifty years.",
        "She received the Presidential Medal of Freedom in 2015, at the age of ninety-seven.",
      ]],
      ["Norman Borlaug", ["agriculture", "variety", "famine", "yield", "resistant"], ["although", "because", "therefore", "consequently", "furthermore"], [
        "Norman Borlaug is probably the least famous person who ever saved a billion lives.",
        "He was a plant scientist who spent twenty years in Mexico breeding wheat.",
        "He was looking for varieties that resisted disease and produced far more grain.",
        "The plants he developed had short, thick stalks, which sounds like a small detail.",
        "Tall wheat falls over under the weight of a heavy head, and fallen wheat rots.",
        "Short wheat could carry a much larger yield without collapsing.",
        "In the 1960s India and Pakistan were facing famine that experts considered unavoidable.",
        "Borlaug's wheat, combined with new farming methods, roughly doubled their harvests within a decade.",
        "Furthermore, the same approach was later applied to rice across Asia.",
        "He won the Nobel Peace Prize in 1970, which surprised him, because he considered himself a farmer.",
      ]],
      ["Marie Curie", ["radioactivity", "element", "research", "laboratory", "persistent"], ["although", "because", "therefore", "consequently", "nevertheless"], [
        "Marie Curie was born in Poland at a time when women could not attend university there.",
        "She studied in secret at an illegal institution that moved between apartments to avoid the authorities.",
        "Eventually she saved enough to move to Paris, where she lived on bread and tea while studying physics.",
        "With her husband Pierre she investigated why certain minerals gave off energy on their own.",
        "To isolate the new elements she processed several tons of a heavy black ore by hand.",
        "It took four years and produced about a tenth of a gram of radium.",
        "She coined the word radioactivity for what she had found.",
        "Curie remains the only person to win Nobel Prizes in two different sciences.",
        "Nevertheless, the work killed her; nobody then understood the danger of what she was handling.",
        "Her laboratory notebooks are still radioactive and are stored in lead-lined boxes.",
      ]],
    ]},
    { title: "Data and Graphs", weeks: [
      ["Choosing a graph", ["compare", "proportion", "category", "axis", "represent"], ["although", "because", "therefore", "consequently", "furthermore"], [
        "Different graphs answer different questions, and picking the wrong one hides your point.",
        "A bar graph compares amounts across categories, which is what it does better than anything else.",
        "A line graph shows change over time, because the line itself implies continuity.",
        "Using a line graph for unrelated categories is a common and misleading error.",
        "A pie chart shows parts of a single whole, and it works only when the parts add to one hundred percent.",
        "Pie charts also fail with more than about five slices, because people cannot compare similar angles.",
        "Every graph needs labeled axes and units, or it is decoration rather than information.",
        "Furthermore, watch where the vertical axis begins.",
        "A bar graph whose axis starts at ninety instead of zero can make a tiny difference look enormous.",
      ]],
      ["Averages", ["mean", "median", "mode", "range", "typical"], ["although", "because", "therefore", "consequently", "nevertheless"], [
        "The word average usually means the mean: add everything up and divide by how many there are.",
        "The mean is useful, but it is easily distorted by extreme values.",
        "Imagine nine people earning thirty thousand dollars and one earning ten million.",
        "The mean income of that group is over a million dollars, which describes nobody in it.",
        "The median is the middle value when you line everything up in order.",
        "In that same group the median is thirty thousand, which describes almost everyone.",
        "The mode is simply the most common value, which matters for things like shoe sizes.",
        "Range is the distance between the largest and smallest, and it tells you how spread out the data is.",
        "Nevertheless, no single number can describe a group honestly on its own.",
        "That is why careful reports give you several, and careless ones give you only the flattering one.",
      ]],
      ["Reading a table", ["column", "row", "category", "compare", "organize"], ["although", "because", "therefore", "consequently", "furthermore"], [
        "A table looks plain, but it holds more information per inch than any graph.",
        "The trick is to read the headings before you read a single number.",
        "Find out what the rows are, what the columns are, and what unit the numbers use.",
        "Thousands, millions and percentages all look identical if you skip the heading.",
        "Then pick one row and read it across to understand the shape of the thing.",
        "After that, pick one column and read it down to compare.",
        "Only then should you start hunting for the number you came for.",
        "Furthermore, look for a footnote, because tables hide their exceptions down there.",
        "A line reading data unavailable for two regions can change what the whole table means.",
      ]],
    ]},
    { title: "Comparing Texts", weeks: [
      ["Two accounts of one event", ["perspective", "emphasis", "omit", "contrast", "account"], ["although", "because", "therefore", "consequently", "nevertheless"], [
        "Two true accounts of the same event can leave completely different impressions.",
        "Neither has to contain a false sentence for this to happen.",
        "The difference comes from emphasis and from what each one leaves out.",
        "A newspaper reporting a protest may lead with the size of the crowd.",
        "Another may lead with the traffic disruption, and a third with the demands being made.",
        "All three are accurate; all three will leave you with a different view.",
        "When you compare texts, start by listing what appears in one and not the other.",
        "Then ask what each author seems to assume their reader already believes.",
        "Nevertheless, comparing does not always produce a winner.",
        "Often the honest conclusion is that you now need a third source.",
      ]],
      ["Fiction and nonfiction on one topic", ["narrative", "factual", "experience", "research", "convey"], ["although", "because", "therefore", "consequently", "furthermore"], [
        "A history book and a novel about the same event do different jobs.",
        "The history book tells you what happened, in order, with evidence.",
        "The novel tells you what it might have felt like to be there.",
        "Neither can replace the other, and treating one as the other causes trouble.",
        "A novel can be emotionally true and factually wrong at the same time.",
        "A history can be factually perfect and leave you understanding nothing about the people.",
        "The best approach is to read both and let each correct the other.",
        "Read the history first, so the novel cannot install false facts in your head.",
        "Furthermore, check the author's note at the back of a historical novel.",
        "Careful novelists tell you exactly where they departed from the record, and why.",
      ]],
      ["Primary and secondary together", ["document", "interpret", "context", "historian", "evidence"], ["although", "because", "therefore", "consequently", "nevertheless"], [
        "A primary source is raw material; a secondary source is what somebody built from it.",
        "A soldier's letter home is primary, and a book about that war is secondary.",
        "Reading only secondary sources means trusting somebody else's selection.",
        "Reading only primary sources means having no context for what you find.",
        "A single letter can be vivid and completely unrepresentative.",
        "The historian's job is to read hundreds and notice the patterns.",
        "Your job as a reader is to notice when a claim rests on one dramatic document.",
        "Look for phrases like one soldier wrote, which may be doing a great deal of work.",
        "Nevertheless, primary sources are where the surprises live.",
        "Almost every revision in history began with somebody reading an old document more carefully.",
      ]],
    ]},
    { title: "Ready for Fifth Grade", weeks: [
      ["Review: roots and affixes", ["constructive", "interrupting", "transportation", "unpredictable", "autobiography"], ["although", "nevertheless", "consequently", "furthermore", "therefore"], [
        "By now you can take apart a word you have never seen.",
        "Autobiography breaks into auto, bio and graph: self, life, writing.",
        "Transportation contains trans and port: carrying across.",
        "Interrupting holds inter and rupt: to break between.",
        "Unpredictable is un, pre, dict and able: not able to be said beforehand.",
        "None of these required you to look anything up.",
        "This is the single most useful reading skill you will build this year.",
        "Vocabulary stops being a list to memorize and becomes a system to decode.",
        "Consequently, the number of words available to you grows far faster than anyone could teach them.",
      ]],
      ["Review: reading for information", ["summarize", "conclude", "analyze", "significant", "relationship"], ["although", "therefore", "furthermore", "consequently", "nevertheless"], [
        "Reading to learn is different from reading for pleasure, and it is a skill you practice.",
        "Start by looking at the headings and pictures before reading a word of the text.",
        "That gives your brain a frame to hang new information on.",
        "As you read, pause at the end of each section and summarize it in one sentence.",
        "If you cannot, you did not understand it, and rereading now is cheaper than rereading later.",
        "Look for the relationship between ideas, not just the ideas themselves.",
        "Did one thing cause another, or did they simply happen near each other?",
        "That distinction is the most significant one in all of nonfiction.",
        "Nevertheless, none of this works if you are reading too fast to notice.",
      ]],
      ["Review: everything", ["persistence", "comprehension", "deliberate", "fluency", "accomplishment"], ["although", "therefore", "consequently", "furthermore", "nevertheless"], [
        "Fluency is not the same thing as speed, although speed is part of it.",
        "A fluent reader decodes words so automatically that attention is free for meaning.",
        "That is why rereading the same passage three times works so well.",
        "The first read is decoding, the second is phrasing, and the third is understanding.",
        "Comprehension improves not because you memorized the passage but because your brain stopped spending effort on the words.",
        "This is deliberate practice, and it is the same thing a musician does with a difficult measure.",
        "Furthermore, the effect transfers.",
        "The fluency you build on one passage makes the next one easier.",
        "Persistence is the whole method, and the accomplishment is real.",
      ]],
    ]},
  ],
};

/** Grade 5: dense informational text, abstract vocabulary. 140–190 words. */
export const GRADE_5: GradeDef = {
  id: "5",
  label: "Grade 5",
  emoji: "5️⃣",
  color: "#f43f5e",
  soft: "#fff1f2",
  wcpm: { fall: 121, winter: 133, spring: 146 },
  units: [
    { title: "Academic Vocabulary", weeks: [
      ["Words about thinking", ["hypothesis", "assumption", "inference", "conclusion", "evidence"], ["although", "whereas", "consequently", "nevertheless", "furthermore"], [
        "Scientists use a vocabulary that sounds formal but describes ordinary mental moves.",
        "An assumption is something you treat as true without checking it.",
        "Everyone makes assumptions constantly; the danger lies in not knowing which ones you have made.",
        "A hypothesis is a proposed explanation that could turn out to be wrong.",
        "That last part matters enormously.",
        "If no possible observation could contradict your idea, it is not a hypothesis.",
        "An inference is a conclusion drawn from evidence rather than observed directly.",
        "You infer that it rained overnight from wet pavement in the morning.",
        "Whereas an observation is what you saw, an inference is what you concluded.",
        "Confusing the two is the most common error in scientific writing.",
        "Nevertheless, inference is unavoidable and often correct.",
        "The goal is not to stop inferring but to label it honestly when you do.",
      ]],
      ["Words about argument", ["counterargument", "concede", "refute", "valid", "assertion"], ["although", "whereas", "consequently", "furthermore", "nevertheless"], [
        "A strong argument does something that feels uncomfortable: it states the other side fairly.",
        "This is called addressing the counterargument, and skipping it weakens your case.",
        "Readers who already disagree with you will think of the objection anyway.",
        "If you have not mentioned it, they conclude you did not know about it.",
        "Sometimes the right move is to concede a point.",
        "Admitting that your opponent is correct about one thing makes your other claims more believable, not less.",
        "To refute a claim is to show it is false, which requires evidence rather than volume.",
        "A valid argument is one whose conclusion follows from its premises.",
        "Notice that a valid argument can still be wrong.",
        "If the premises are false, perfect logic will carry you straight to a false conclusion.",
        "Furthermore, most real disagreements are not about logic at all.",
        "They are about which facts matter most, which is a harder thing to settle.",
      ]],
      ["Words about systems", ["interdependent", "equilibrium", "feedback", "variable", "stability"], ["whereas", "although", "consequently", "nevertheless", "furthermore"], [
        "A system is a set of parts whose behavior depends on one another.",
        "The parts are interdependent, which means you cannot understand one by studying it alone.",
        "Feedback is what happens when the output of a system loops back as an input.",
        "Negative feedback pushes a system back toward balance, like a thermostat.",
        "When a room cools, the heater runs; when it warms, the heater stops.",
        "That balance point is called equilibrium, and it produces stability.",
        "Positive feedback does the opposite: it amplifies a change.",
        "Ice reflects sunlight, so melting ice means less reflection, which means more warming and more melting.",
        "Consequently, systems with strong positive feedback can shift suddenly rather than gradually.",
        "A variable is anything in the system that can change.",
        "Furthermore, changing one variable almost never changes only one thing.",
        "That is the central difficulty, and the central interest, of studying any system at all.",
      ]],
    ]},
    { title: "Reading Science", weeks: [
      ["Antibiotic resistance", ["bacteria", "resistance", "mutation", "selection", "prescribe"], ["although", "whereas", "consequently", "nevertheless", "furthermore"], [
        "When Alexander Fleming accepted his Nobel Prize in 1945, he issued a warning.",
        "He said that bacteria could become resistant to penicillin, and that careless use would make it happen faster.",
        "He was right, and the mechanism is straightforward.",
        "Bacteria reproduce enormously fast, and copying mistakes called mutations occur constantly.",
        "Most mutations are useless or harmful, but occasionally one lets a bacterium survive a drug.",
        "If you take an antibiotic and stop early, you kill the weakest bacteria and leave the toughest alive.",
        "Those survivors reproduce without competition.",
        "This is natural selection operating on a timescale of days rather than millennia.",
        "Consequently, the problem is not that bacteria are becoming cleverer.",
        "It is that we keep running the experiment that selects for resistance.",
        "Doctors now prescribe antibiotics more carefully, and finishing the full course matters more than most people realize.",
        "Nevertheless, some infections that were routinely curable in 1980 are becoming difficult to treat again.",
      ]],
      ["Plate tectonics", ["continental", "subduction", "ridge", "convection", "geological"], ["although", "whereas", "consequently", "furthermore", "nevertheless"], [
        "In 1912 Alfred Wegener noticed that the coastlines of South America and Africa fit together.",
        "He proposed that the continents had once been joined and had drifted apart.",
        "Geologists rejected the idea for almost fifty years, and for a defensible reason.",
        "Wegener could not explain what force could possibly move a continent.",
        "The answer arrived in the 1960s from the ocean floor.",
        "Mapping revealed a ridge running down the middle of the Atlantic where new crust is created.",
        "Rock gets older in both directions as you move away from it.",
        "The Atlantic is spreading, roughly as fast as your fingernails grow.",
        "Convection in the hot mantle below drives the motion.",
        "Where plates collide, one slides beneath the other in a process called subduction.",
        "Consequently, the deepest ocean trenches and the tallest mountains are produced by the same mechanism.",
        "Wegener died on an expedition in Greenland in 1930, thirty years before he was proved right.",
      ]],
      ["Light and color", ["spectrum", "wavelength", "absorb", "reflect", "perception"], ["whereas", "although", "consequently", "furthermore", "nevertheless"], [
        "Objects do not have color in the way they have mass.",
        "What an object has is a tendency to absorb some wavelengths of light and reflect others.",
        "A leaf absorbs most red and blue light and reflects green, which is why it looks green to you.",
        "In complete darkness the leaf has no color at all.",
        "White light contains the entire visible spectrum mixed together.",
        "A prism separates it because different wavelengths bend by different amounts as they pass through glass.",
        "Your eye contains three kinds of cone cells, sensitive to roughly red, green and blue.",
        "Every color you have ever seen is your brain comparing the signals from those three.",
        "Consequently, color is partly a property of the world and partly a construction of your nervous system.",
        "Some animals have four or more cone types and can see wavelengths invisible to us.",
        "Furthermore, a few people inherit a fourth cone as well.",
        "Nevertheless, we have no way to know whether what they see resembles anything we could imagine.",
      ]],
    ]},
    { title: "Reading History", weeks: [
      ["The Dust Bowl", ["erosion", "drought", "migration", "agriculture", "devastating"], ["although", "whereas", "consequently", "nevertheless", "furthermore"], [
        "The Dust Bowl of the 1930s was a natural disaster that people helped build.",
        "The southern plains had always been dry and windy, held together by deep-rooted prairie grass.",
        "During the First World War wheat prices rose sharply, and farmers plowed millions of acres of that grass under.",
        "For a decade the rains were generous and the crops were enormous.",
        "Then, in 1931, the rain stopped.",
        "With no roots to hold it, the topsoil simply lifted into the air.",
        "Storms carried dust as far as ships in the Atlantic Ocean.",
        "On a single day in April 1935, remembered as Black Sunday, visibility fell to a few feet.",
        "Consequently, hundreds of thousands of families abandoned their farms and moved west.",
        "The federal government responded by planting two hundred million trees as windbreaks and teaching contour plowing.",
        "Furthermore, the Soil Conservation Service created in 1935 still exists today.",
        "The lesson was expensive, and it was learned.",
      ]],
      ["The Underground Railroad", ["abolitionist", "conductor", "fugitive", "perilous", "network"], ["although", "whereas", "consequently", "nevertheless", "furthermore"], [
        "The Underground Railroad was neither underground nor a railroad.",
        "It was a loose network of people, routes and hiding places that helped enslaved people reach freedom.",
        "The railroad vocabulary was deliberate: safe houses were stations and guides were conductors.",
        "Because secrecy was essential, almost nothing was written down.",
        "Consequently, historians still argue about how many people escaped this way.",
        "Estimates range from thirty thousand to one hundred thousand over several decades.",
        "Harriet Tubman is the best known conductor, and she returned to the South roughly thirteen times.",
        "She later said she never lost a passenger.",
        "The work was perilous for everyone involved.",
        "After the Fugitive Slave Act of 1850, even helping someone in a free state became a federal crime.",
        "Furthermore, many escapes continued all the way to Canada because no part of the United States was safe.",
        "The courage required is difficult to overstate.",
      ]],
      ["The space race", ["satellite", "orbit", "cosmonaut", "milestone", "ambitious"], ["although", "whereas", "consequently", "nevertheless", "furthermore"], [
        "On October 4, 1957, the Soviet Union launched a metal sphere the size of a beach ball into orbit.",
        "Sputnik carried nothing but a radio transmitter and a battery.",
        "Its beeping could be picked up by amateur radio operators anywhere on Earth.",
        "The American reaction was closer to panic than curiosity.",
        "If a rocket could place a satellite over New York, it could place something else there too.",
        "Congress responded by founding NASA within a year and pouring money into science education.",
        "The Soviets reached each early milestone first: the first animal, the first man, the first woman in orbit.",
        "Yuri Gagarin completed a single orbit in April 1961.",
        "Consequently, President Kennedy chose a goal far enough away that the United States might still win it.",
        "Landing a human on the Moon was absurdly ambitious in 1961.",
        "Nevertheless, it happened eight years later, with computers less powerful than a modern calculator.",
        "Roughly four hundred thousand people worked on the program.",
      ]],
    ]},
    { title: "Reading Critically", weeks: [
      ["Evaluating sources", ["credibility", "bias", "citation", "corroborate", "scrutiny"], ["although", "whereas", "consequently", "nevertheless", "furthermore"], [
        "Anyone can publish anything, which makes evaluating sources a survival skill.",
        "Credibility is not about whether writing sounds confident.",
        "Confident writing is easy to produce and tells you nothing about accuracy.",
        "Instead, look for citations: does the author say where the information came from?",
        "A source that cannot be checked cannot be trusted, however reasonable it sounds.",
        "Bias is not the same thing as dishonesty.",
        "Every writer has a perspective, and knowing what it is helps you read them accurately.",
        "The question is not whether a source is biased but whether it is still useful once you account for the bias.",
        "Corroboration is the strongest tool you have.",
        "Two independent sources reporting the same fact is far stronger evidence than one source stating it emphatically.",
        "Furthermore, be especially skeptical of claims you already want to believe.",
        "Those are the ones that slip past your scrutiny.",
      ]],
      ["Statistics in the news", ["correlation", "causation", "sample", "average", "misleading"], ["although", "whereas", "consequently", "nevertheless", "furthermore"], [
        "Numbers in a headline feel objective, but they can mislead without containing a single falsehood.",
        "The most common error is confusing correlation with causation.",
        "Ice cream sales and drowning deaths rise together every summer.",
        "Ice cream does not cause drowning; hot weather causes both.",
        "A second problem is the sample.",
        "A survey of a thousand people can describe a nation accurately, but only if those thousand were chosen properly.",
        "A poll of people who chose to respond describes people who like answering polls.",
        "The word average hides a third trap.",
        "If nine people earn thirty thousand dollars and one earns ten million, the average income is over a million.",
        "Consequently, the median is often more honest than the mean.",
        "Furthermore, a percentage with no base number is nearly meaningless.",
        "A hundred percent increase sounds alarming until you learn it went from one case to two.",
      ]],
      ["Reading for a lifetime", ["sustained", "comprehension", "deliberate", "transferable", "cumulative"], ["although", "whereas", "consequently", "nevertheless", "furthermore"], [
        "The research on reading points to something slightly unglamorous.",
        "The strongest predictor of how well someone reads at eighteen is how much they read between eight and twelve.",
        "Not which books, and not how difficult: how much.",
        "Vocabulary growth is cumulative and quiet.",
        "A child who reads twenty minutes a day encounters roughly 1.8 million words a year.",
        "A child who reads one minute a day encounters about eight thousand.",
        "After six years that gap is unbridgeable by instruction alone.",
        "This is why fluency work matters so much early on.",
        "Reading that feels effortful does not get done voluntarily, and reading that is not voluntary stays small.",
        "Consequently, the three timed reads you have been doing are not really about speed.",
        "They are about making reading cheap enough that you will choose to do it.",
        "Nevertheless, the choosing is still yours, and it always will be.",
      ]],
    ]},
    { title: "Reading Geography", weeks: [
      ["Ocean currents", ["circulation", "salinity", "thermal", "gyre", "regulate"], ["although", "whereas", "consequently", "nevertheless", "furthermore"], [
        "The ocean is not a still bathtub; it moves in enormous, predictable loops called gyres.",
        "Surface currents are driven mostly by wind, and they bend because the Earth is rotating.",
        "Deeper circulation is driven by density, which depends on temperature and salinity.",
        "Cold, salty water is heavy and sinks; warm, fresher water is light and rises.",
        "Near Greenland, surface water cools, grows dense and plunges toward the sea floor.",
        "That sinking pulls warm water north behind it, carrying heat from the tropics toward Europe.",
        "Consequently London sits farther north than much of Canada yet has far milder winters.",
        "This global loop takes roughly a thousand years to complete one circuit.",
        "Furthermore, it regulates climate on a scale no human system comes close to matching.",
        "Scientists watch it closely, because meltwater adds fresh water exactly where the sinking happens.",
      ]],
      ["Why borders are where they are", ["boundary", "colonial", "arbitrary", "negotiate", "territory"], ["although", "whereas", "consequently", "furthermore", "nevertheless"], [
        "Look at a map of Africa and you will notice something odd: many borders are perfectly straight.",
        "Rivers and mountain ranges do not run in straight lines, and neither do communities.",
        "Those borders were drawn in European capitals, largely at a conference in Berlin in 1884.",
        "Almost nobody present had been to the places they were dividing.",
        "Lines were negotiated between empires with a ruler and a small-scale map.",
        "Consequently single ethnic groups were split across three countries, and rival groups were sealed into one.",
        "When independence came, most new nations kept the colonial borders rather than redraw them.",
        "The reasoning was practical: reopening every boundary at once risked endless war.",
        "Nevertheless, those arbitrary lines remain a source of conflict more than sixty years later.",
        "Geography on a map is never only geography; it is also a record of who held power when the pen moved.",
      ]],
      ["Population and migration", ["density", "urbanization", "demographic", "displacement", "projection"], ["although", "whereas", "consequently", "furthermore", "nevertheless"], [
        "For most of human history the population grew so slowly it was almost invisible.",
        "It took until around 1804 to reach one billion people.",
        "The second billion took roughly a century; the seventh took about twelve years.",
        "That acceleration was not caused by people having far more children.",
        "It was caused by far more children surviving, thanks to clean water, vaccines and better food.",
        "Growth is now slowing sharply as families in most countries choose to have fewer children.",
        "Demographers project the world population will peak this century and then decline.",
        "Migration moves people around that total, and most migration is internal rather than between countries.",
        "Furthermore, the largest movement in history is still underway: the shift from countryside to city.",
        "Nevertheless, projections are not promises; they are arithmetic applied to assumptions that may not hold.",
      ]],
    ]},
    { title: "Literary Language", weeks: [
      ["Voice and point of view", ["narrator", "unreliable", "omniscient", "intimate", "perspective"], ["although", "whereas", "consequently", "nevertheless", "furthermore"], [
        "Who is telling the story changes the story, even if every event stays the same.",
        "A first-person narrator says I, and you are locked inside one head.",
        "That creates intimacy, but it also means you only know what that person knows.",
        "Writers exploit this with the unreliable narrator, who misunderstands or lies.",
        "The pleasure for the reader is noticing the gap before the narrator does.",
        "Third-person limited stays outside but follows one character closely.",
        "Third-person omniscient can enter any head and see the whole board.",
        "Omniscience is powerful, whereas limited perspective creates suspense, because the reader cannot see around corners either.",
        "Furthermore, the choice is never neutral.",
        "A story about a war told by a general and the same story told by a child are not the same story at all.",
      ]],
      ["Irony", ["contrast", "expectation", "sincere", "dramatic", "situational"], ["although", "whereas", "consequently", "furthermore", "nevertheless"], [
        "Irony is a gap between what is expected and what actually happens or is meant.",
        "Verbal irony is saying the opposite of what you mean, and tone usually carries it.",
        "Calling a downpour lovely weather is the simplest version.",
        "Situational irony is when events turn out backward from what anyone would expect.",
        "A fire station burning down is the textbook example.",
        "Dramatic irony is the most powerful: the audience knows something a character does not.",
        "Every horror film relies on it, and so does most tragedy.",
        "The audience watching a character walk cheerfully toward disaster feels dread the character cannot.",
        "Furthermore, irony is fragile across cultures and in writing without tone of voice.",
        "Nevertheless, used carefully it does something no plain statement can: it makes the reader a participant.",
      ]],
      ["Theme", ["underlying", "universal", "explicit", "implicit", "resonance"], ["although", "whereas", "consequently", "nevertheless", "furthermore"], [
        "A theme is not the subject of a story; it is what the story says about that subject.",
        "The subject might be war, and the theme might be that ordinary people pay for decisions made far above them.",
        "Themes are usually implicit, because a story that states its theme outright feels like a lecture.",
        "You find a theme by noticing what repeats and what the ending rewards or punishes.",
        "Ask what the main character believed at the start and whether they still believe it.",
        "The gap between those two positions is often where the theme lives.",
        "A story can carry several themes at once, and readers can reasonably disagree about them.",
        "That disagreement is not a flaw; it is why books stay interesting for centuries.",
        "Furthermore, a theme that can be reduced to a single moral sentence is usually a weak one.",
      ]],
    ]},
    { title: "Reading About People", weeks: [
      ["Alan Turing", ["cryptography", "algorithm", "theoretical", "persecution", "foundation"], ["although", "whereas", "consequently", "nevertheless", "furthermore"], [
        "In 1936, before any electronic computer existed, Alan Turing described one on paper.",
        "His imaginary machine read symbols from a tape and followed rules written in a table.",
        "He proved that such a machine could compute anything that could be computed at all.",
        "That paper is the theoretical foundation of every computer you have ever used.",
        "During the Second World War he worked at Bletchley Park breaking German naval codes.",
        "The Enigma machine had so many settings that checking them by hand was hopeless.",
        "Turing's team built electromechanical machines that eliminated wrong settings fast enough to matter.",
        "Historians estimate the work shortened the war by roughly two years.",
        "Nevertheless, in 1952 he was prosecuted for being gay, which was then a crime in Britain.",
        "He died two years later, and the official apology came fifty-five years after that.",
      ]],
      ["Rachel Carson", ["pesticide", "ecosystem", "accumulate", "testimony", "legislation"], ["although", "whereas", "consequently", "furthermore", "nevertheless"], [
        "Rachel Carson was a marine biologist who wrote unusually well, which turned out to matter enormously.",
        "In the 1950s the pesticide DDT was sprayed widely and considered entirely safe.",
        "Carson gathered evidence that it accumulated in animal tissue and moved up the food chain.",
        "Insects carried small amounts; the birds that ate them carried more; the hawks that ate those birds carried most.",
        "Eggshells thinned until they broke under the weight of the parent, and whole populations collapsed.",
        "Silent Spring was published in 1962 and was attacked immediately by chemical companies.",
        "She was accused of being hysterical and unscientific, and she was dying of cancer as she defended the work.",
        "She testified before Congress in 1963, calmly, with her evidence in order.",
        "Furthermore, her book is widely credited with starting the modern environmental movement.",
        "DDT was banned in the United States in 1972, and the bald eagle recovered.",
      ]],
      ["Shirley Chisholm", ["congress", "campaign", "nomination", "obstacle", "principle"], ["although", "whereas", "consequently", "nevertheless", "furthermore"], [
        "Shirley Chisholm was elected to Congress in 1968, the first Black woman ever to serve there.",
        "Her campaign slogan was Unbought and Unbossed, and she meant both halves of it literally.",
        "On arriving she was assigned to the Agriculture Committee, which had nothing to do with her Brooklyn district.",
        "She objected publicly, which was not how new members were expected to behave.",
        "She was reassigned, and she used the position to expand food stamps and help create a nutrition program for mothers and children.",
        "In 1972 she ran for the Democratic presidential nomination.",
        "She was blocked from televised debates and had to sue for the right to speak once.",
        "She won twenty-eight delegates, and she never expected to win the nomination.",
        "Furthermore, she said plainly that she ran so that it would be ordinary for someone like her to run.",
        "Nevertheless, she described herself first as a teacher, which is what she had trained to be.",
      ]],
    ]},
    { title: "Money and Society", weeks: [
      ["What money actually is", ["currency", "value", "exchange", "trust", "inflation"], ["although", "whereas", "consequently", "nevertheless", "furthermore"], [
        "A twenty dollar bill is a piece of paper worth almost nothing as paper.",
        "It has value because everyone agrees it does, and for no other reason.",
        "Before money, trade required a coincidence of wants.",
        "If you had wheat and needed shoes, you had to find a shoemaker who happened to want wheat.",
        "Money solves that by being something everyone will accept, which makes it a store of value.",
        "For most of history that something was a metal that was scarce and hard to fake.",
        "Modern currency is backed by nothing physical; it is backed entirely by confidence in a government.",
        "Consequently inflation is not only an economic event but a crisis of trust.",
        "When people stop believing the paper will hold its value, they spend it faster, which pushes prices up further.",
        "Furthermore, this is why central banks guard their credibility as carefully as their reserves.",
      ]],
      ["Supply and demand", ["scarcity", "surplus", "equilibrium", "incentive", "allocate"], ["although", "whereas", "consequently", "furthermore", "nevertheless"], [
        "Price is not a fact about an object; it is a signal about scarcity.",
        "When something becomes harder to get, the price rises, and the rise does two jobs at once.",
        "It discourages some buyers, which stretches the limited supply further.",
        "It also encourages producers to make more, because there is now more money in doing so.",
        "Both effects push toward a balance point called equilibrium.",
        "When supply exceeds demand, the opposite happens and the price falls until the surplus clears.",
        "This is why price controls often produce shortages rather than fairness.",
        "Holding a price below equilibrium removes the incentive to produce more of exactly the thing that is scarce.",
        "Nevertheless, markets allocate efficiently, not justly.",
        "Efficiency says who can pay the most; it says nothing at all about who needs it most.",
      ]],
      ["Reading a budget", ["revenue", "expenditure", "deficit", "allocate", "priority"], ["although", "whereas", "consequently", "furthermore", "nevertheless"], [
        "A budget is a moral document disguised as a spreadsheet.",
        "Revenue is money coming in; expenditure is money going out.",
        "When expenditure exceeds revenue the difference is a deficit, and it has to be borrowed.",
        "Accumulated deficits over many years become the debt, which are different things people often confuse.",
        "Reading a budget well means ignoring the totals at first and looking at the proportions.",
        "What share goes to schools, to roads, to health, to paying interest on past borrowing?",
        "Those shares tell you what the people who wrote it actually value, whatever the speeches claimed.",
        "Watch also for one-time items presented as if they were permanent savings.",
        "Furthermore, compare this year's budget to last year's rather than reading it alone.",
        "A number only becomes meaningful next to the number it replaced.",
      ]],
    ]},
    { title: "Argument and Evidence", weeks: [
      ["Logical fallacies", ["fallacy", "reasoning", "assumption", "generalize", "attribute"], ["although", "whereas", "consequently", "nevertheless", "furthermore"], [
        "A fallacy is an argument that feels convincing but does not actually work.",
        "Attacking the person instead of the claim is the most common one.",
        "Whether someone is unpleasant has no bearing on whether their evidence is sound.",
        "The false dilemma offers two options when more exist: either we do this or we do nothing.",
        "Hasty generalization draws a rule from too few cases, usually cases the speaker happened to notice.",
        "The slippery slope claims one small step leads inevitably to disaster, without showing the steps between.",
        "Appeal to popularity says a thing is true because many people believe it, which history refutes repeatedly.",
        "Furthermore, recognizing a fallacy does not prove the conclusion is false.",
        "A bad argument for a true claim is still a bad argument, and the claim still needs a good one.",
      ]],
      ["Weighing evidence", ["anecdote", "sample", "replicate", "peer-review", "significance"], ["although", "whereas", "consequently", "furthermore", "nevertheless"], [
        "Not all evidence carries the same weight, and knowing the order matters.",
        "An anecdote is a single story, and it is the weakest form of evidence there is.",
        "It is also the most persuasive, which is precisely the problem.",
        "A study with a large, randomly chosen sample is far stronger than a hundred anecdotes.",
        "A study that has been replicated by independent researchers is stronger still.",
        "Peer review means other experts checked the method before publication, which filters out obvious errors.",
        "Nevertheless, peer review is not a guarantee, and a surprising number of published results fail to replicate.",
        "When a single dramatic study contradicts a large body of earlier work, the sensible response is patience.",
        "Furthermore, ask who funded the research and whether that party had a preferred answer.",
      ]],
      ["Building your own argument", ["thesis", "evidence", "concede", "structure", "persuasive"], ["although", "whereas", "consequently", "furthermore", "nevertheless"], [
        "A strong argument starts with a thesis you could actually be wrong about.",
        "If no evidence could change your mind, you are not arguing; you are announcing.",
        "State the claim plainly and early, because a reader who cannot find your point stops looking.",
        "Then give your strongest evidence first, not last.",
        "Readers decide early whether to trust you, and your best material has to arrive before that happens.",
        "Address the strongest version of the opposing view, not the weakest one you can find.",
        "Beating a weak version persuades nobody who disagreed with you to begin with.",
        "Concede whatever is genuinely true on the other side, which costs you nothing and buys enormous credibility.",
        "Furthermore, end with what follows from your claim rather than with a summary.",
        "A reader who has followed you this far does not need to be told what they just read.",
      ]],
    ]},
    { title: "Ready for Middle School", weeks: [
      ["Reading in every subject", ["discipline", "terminology", "notation", "density", "strategy"], ["although", "whereas", "consequently", "furthermore", "nevertheless"], [
        "Middle school will hand you a different reading problem in every class.",
        "A science textbook is dense, with meaning packed into terminology that cannot be skipped.",
        "You read it slowly, stopping at every unfamiliar term, because the next paragraph assumes it.",
        "A history text is less dense but longer, and the skill is tracking cause across pages.",
        "A math text is the densest of all; a single line can take fifteen minutes and that is normal.",
        "Literature asks you to read quickly for the story and then slowly for everything else.",
        "Reading all four at the same speed is the most common mistake students make.",
        "Furthermore, nobody announces which mode a text requires; you work it out from the first page.",
        "Nevertheless, the underlying fluency is the same one you have been building all along.",
      ]],
      ["Taking notes", ["summarize", "paraphrase", "hierarchy", "retrieval", "condense"], ["although", "whereas", "consequently", "nevertheless", "furthermore"], [
        "Copying sentences from a book is not taking notes; it is handwriting practice.",
        "Useful notes require you to put an idea into your own words, which forces understanding.",
        "If you cannot paraphrase a sentence, you have found exactly the thing you do not yet understand.",
        "Good notes show hierarchy: which ideas are main and which are supporting.",
        "Indentation does this better than any amount of highlighting.",
        "Leave a wide margin and write questions in it as you go.",
        "Later, cover the notes and try to answer those questions from memory.",
        "That act of retrieval is what moves information into long-term memory.",
        "Furthermore, rereading feels productive and is almost useless by comparison.",
        "Testing yourself feels harder precisely because it is doing more work.",
      ]],
      ["Where this goes", ["independent", "curiosity", "sustained", "cumulative", "lifelong"], ["although", "whereas", "consequently", "furthermore", "nevertheless"], [
        "You have now read your way from a cat on a mat to arguments about evidence and economics.",
        "That happened one passage at a time, three reads a day, over a long stretch of ordinary afternoons.",
        "None of it was dramatic, and that is the actual lesson.",
        "Fluency is cumulative in a way that cannot be rushed or skipped.",
        "From here the reading stops being assigned and starts being chosen.",
        "Nobody will set you a passage or time you on it.",
        "What you have instead is the ability to pick up almost anything and get through it.",
        "That ability is quiet and invisible, and it will shape what is available to you for the rest of your life.",
        "Furthermore, the only thing required to keep it is to keep using it.",
        "Go and read something nobody told you to read.",
      ]],
    ]},
  ],
};
