import type { GradeDef } from "./types";

/** Grade 2: vowel teams, r-controlled, diphthongs, suffixes. 55–110 words. */
export const GRADE_2: GradeDef = {
  id: "2",
  label: "Grade 2",
  emoji: "2️⃣",
  color: "#0ea5e9",
  soft: "#f0f9ff",
  wcpm: { fall: 50, winter: 84, spring: 100 },
  units: [
    { title: "Review and Launch", weeks: [
      ["Short vowels and blends", ["splash", "crunch", "stand", "blend", "strong"], ["against", "already", "almost", "behind", "between"], [
        "The path behind our house runs between two fields.",
        "In summer the grass grows almost as tall as I am.",
        "I like to stand at the top and look out over everything.",
        "The wind pushes against me, strong enough to make me lean.",
        "Below, the creek makes a steady splash against the rocks.",
        "Dry leaves crunch under my feet the whole way down.",
        "By the time I get there, I have already forgotten whatever was bothering me.",
      ]],
      ["Digraphs", ["should", "watch", "reach", "shrink", "thought"], ["another", "through", "enough", "nothing", "everything"], [
        "My grandfather taught me to watch the sky before a storm.",
        "He said you can tell enough from the clouds to know what is coming.",
        "When they shrink back and the air goes still, something is on the way.",
        "I thought he was teasing me, but he was right every single time.",
        "Now I watch for it too, through the kitchen window.",
        "Nothing makes me feel closer to him than another good storm.",
      ]],
      ["Magic e", ["whole", "those", "shine", "brave", "chase"], ["important", "different", "beautiful", "probably", "remember"], [
        "The lake looks completely different at sunrise.",
        "The whole surface begins to shine before the sun is even up.",
        "Those first few minutes are probably the most beautiful of the day.",
        "A brave heron stands in the shallows, waiting.",
        "When a fish moves, he does not chase it — he simply strikes.",
        "My father says the important part is learning to be still.",
        "I am still learning, but I remember what he told me.",
      ]],
    ]},
    { title: "Vowel Teams", weeks: [
      ["ai and ay", ["afraid", "explain", "contain", "display", "delay"], ["certain", "several", "usually", "although", "perhaps"], [
        "The museum has a display of fossils near the front door.",
        "Although I have seen it several times, I always stop.",
        "The largest case contains a jaw with teeth longer than my hand.",
        "A guide usually waits nearby to explain how old they are.",
        "I am certain I asked her the same question twice last year.",
        "She did not seem to mind the delay, or perhaps she was being kind.",
        "I used to be afraid of that jaw when I was small.",
      ]],
      ["ee and ea", ["succeed", "repeat", "beneath", "freedom", "increase"], ["because", "between", "without", "beyond", "whether"], [
        "The garden beneath our window was my grandmother's.",
        "She planted the same seeds every spring without fail.",
        "Whether the summer was wet or dry, something always grew.",
        "She said the secret was to repeat the work, not to repeat the worry.",
        "Between the rows she left space, because crowded plants never succeed.",
        "Each year the beds increase a little beyond where they were.",
        "I keep them going now, and I keep her habits too.",
      ]],
      ["oa and ow", ["approach", "throat", "floating", "borrow", "narrow"], ["often", "around", "toward", "beneath", "across"], [
        "A narrow wooden bridge crosses the creek near the mill.",
        "You have to approach it slowly, because two boards are loose.",
        "I often stop halfway and look down at the water.",
        "Leaves come floating toward me and pass beneath my feet.",
        "Once I dropped my hat and had to borrow my brother's for a week.",
        "He reminded me about it every single day until I got it back.",
        "The creek still has my hat somewhere, I think.",
      ]],
    ]},
    { title: "More Vowel Teams", weeks: [
      ["igh and ie", ["frightened", "delight", "slightly", "brief", "achieve"], ["suddenly", "although", "finally", "already", "quietly"], [
        "A thunderstorm woke me in the middle of the night.",
        "At first I was frightened, although I am too old to admit it.",
        "The lightning lit my room so brightly it looked like noon.",
        "Then, just as suddenly, everything went quiet.",
        "I crept to the window and watched the clouds slide slightly apart.",
        "Behind them the moon was already waiting.",
        "It was brief, but seeing it felt like an achievement.",
      ]],
      ["oo (both sounds)", ["smooth", "choose", "crooked", "understood", "cookbook"], ["through", "should", "neither", "whether", "especially"], [
        "My aunt keeps a cookbook with a crooked spine on the counter.",
        "The pages are smooth from being turned so many times.",
        "Neither she nor I follow it exactly, especially the baking parts.",
        "She says you should choose the recipe and then make it your own.",
        "The first time I understood what she meant, I was eleven.",
        "I had added too much cinnamon, and it turned out better that way.",
      ]],
      ["ue and ew", ["argue", "rescue", "continue", "knew", "threw"], ["usually", "nothing", "several", "already", "eventually"], [
        "Our dog was a rescue, and she is afraid of almost nothing.",
        "She usually sleeps through thunder and fireworks alike.",
        "But she will not continue down the hallway if a bag is on the floor.",
        "We argue about why, and we have for several years.",
        "My sister knew a trick: she threw a treat past it once.",
        "Eventually the dog walked by, and now she barely notices.",
      ]],
    ]},
    { title: "Bossy R", weeks: [
      ["ar", ["sharpen", "departure", "harvest", "particular", "remarkable"], ["through", "beyond", "whether", "although", "necessary"], [
        "Harvest week is the busiest week of the year on my uncle's farm.",
        "He sharpens every blade the night before, which is necessary.",
        "Although he has help, he does the first pass alone.",
        "He is particular about the order the fields are cut.",
        "I asked him why, and he said each one dries differently.",
        "Watching him work through a whole field is remarkable.",
        "By the departure of the last truck, the sun is already down.",
      ]],
      ["or and ore", ["important", "forward", "therefore", "explore", "ignore"], ["enough", "against", "between", "beyond", "several"], [
        "The old lighthouse has been closed for several years.",
        "A sign on the gate tells visitors to go no further.",
        "Most people ignore the beach beyond it, which suits me.",
        "I go there to explore the tide pools between the rocks.",
        "You have to move forward carefully; the stones are slick.",
        "It is important not to lean against the rail at the top.",
        "The salt air has eaten through more of it than anyone realizes.",
      ]],
      ["er, ir, ur", ["surprise", "burden", "thirsty", "perfect", "further"], ["already", "whether", "usually", "although", "certainly"], [
        "My grandmother turned ninety last Thursday.",
        "She certainly did not want a surprise party, so we had one anyway.",
        "She said the whole thing was a burden, but she was smiling.",
        "By the end she had told the same story three times.",
        "It was the one about walking further than she needed to for water.",
        "She was thirsty, she said, but the long way was prettier.",
        "That is a perfect summary of my grandmother.",
      ]],
    ]},
    { title: "Tricky Vowels", weeks: [
      ["ou and ow", ["announce", "surround", "allowance", "powerful", "mountain"], ["through", "beyond", "already", "whether", "although"], [
        "Mountains surround the valley where my cousins live.",
        "In the morning the clouds sit so low you cannot see beyond the barn.",
        "By noon they burn off and the peaks announce themselves.",
        "The wind coming down is powerful enough to rattle the windows.",
        "I saved my allowance for a whole year to visit.",
        "Although the trip was long, I would do it again tomorrow.",
      ]],
      ["oi and oy", ["destroy", "avoid", "loyal", "appoint", "moisture"], ["because", "nothing", "whether", "several", "eventually"], [
        "A storm last October nearly destroyed the old oak by the road.",
        "Half of it came down, and nothing we did seemed to help.",
        "My father tried to avoid cutting the rest, because he grew up under it.",
        "He asked several people whether it could be saved.",
        "Eventually a woman from the county came out to look.",
        "She said the trunk still held moisture and had years left in it.",
        "That tree has been loyal to our family for a long time.",
      ]],
      ["au and aw", ["caution", "applaud", "exhausted", "awkward", "laundry"], ["although", "through", "enough", "several", "finally"], [
        "The school play ran three nights in a row.",
        "By the last one we were all completely exhausted.",
        "My costume was awkward and I nearly tripped twice.",
        "Our teacher kept telling us to move with caution near the edge.",
        "Although I forgot one line, nobody in the audience noticed.",
        "When the lights came up they began to applaud, and it went on long enough to make me blush.",
        "The next morning there was a mountain of laundry waiting.",
      ]],
    ]},
    { title: "Words That Grow", weeks: [
      ["Prefixes un- and re-", ["unusual", "rebuild", "unable", "return", "unfair"], ["although", "because", "several", "certainly", "eventually"], [
        "The treehouse my father built came down in a storm.",
        "We were unable to save most of the boards.",
        "It seemed unfair, because it had stood for eleven years.",
        "Although he said nothing that day, he returned the next weekend with lumber.",
        "It is unusual for him to take on a project that size alone.",
        "It took most of the summer to rebuild, and it is better than before.",
        "Eventually my own children will climb it, I hope.",
      ]],
      ["Suffixes -ful and -less", ["careful", "helpful", "endless", "hopeless", "peaceful"], ["through", "already", "whether", "nothing", "several"], [
        "Learning to sail looked hopeless the first afternoon.",
        "There were several ropes and I could not keep them straight.",
        "My instructor was patient and helpful, even when I tangled everything.",
        "Be careful with the boom, she kept saying, and she was right to.",
        "By the third day something clicked and the work felt endless but good.",
        "Out past the point the water went flat and peaceful.",
        "Nothing has ever made me feel quite like that did.",
      ]],
      ["Suffixes -er and -est", ["brighter", "quietest", "stronger", "earliest", "gentlest"], ["although", "because", "usually", "finally", "certainly"], [
        "My older brother is stronger than me and always will be.",
        "But he is also the gentlest person in our family.",
        "He usually wakes at the earliest hour, before anyone else.",
        "The house is at its quietest then, and he likes it that way.",
        "Although he never says much, he notices everything.",
        "When I had a bad week he made my favorite dinner without being asked.",
        "The kitchen seemed brighter just because he was in it.",
      ]],
    ]},
    { title: "Contractions and Plurals", weeks: [
      ["Contractions", ["wouldn't", "couldn't", "they're", "shouldn't", "we've"], ["through", "already", "several", "because", "finally"], [
        "We've driven to the coast every August since I was four.",
        "They're long days, and my sister and I couldn't sit still.",
        "Dad said we shouldn't ask how much further, so we asked anyway.",
        "He wouldn't tell us, which only made it worse.",
        "Finally the air would change and we'd smell salt through the window.",
        "That smell still means summer to me, and it always will.",
      ]],
      ["Tricky plurals", ["leaves", "wolves", "children", "shelves", "stories"], ["beyond", "through", "although", "several", "eventually"], [
        "The library on Oak Street has shelves that reach the ceiling.",
        "A rolling ladder runs along them, and children are not allowed to use it.",
        "I asked the librarian for stories about wolves.",
        "She came back with four books and a map of where they live.",
        "Although I only wanted one, I checked out all of them.",
        "Outside, the leaves had started to turn while I was inside.",
        "Eventually I read every book she gave me, twice.",
      ]],
      ["Possessives", ["sister's", "children's", "father's", "team's", "everyone's"], ["through", "because", "already", "several", "finally"], [
        "My sister's bike was stolen from the front porch in May.",
        "It was my father's bike before that, and his father's before him.",
        "Everyone's first thought was that it was gone for good.",
        "Then a neighbor spotted it behind the children's library.",
        "The frame was scratched, but the team's mechanic fixed it in an hour.",
        "Finally my sister rode it home, and she has not left it outside since.",
      ]],
    ]},
    { title: "Reading to Learn", weeks: [
      ["Science: weather", ["temperature", "pressure", "forecast", "humidity", "atmosphere"], ["because", "through", "although", "several", "usually"], [
        "A weather forecast is really just a careful guess.",
        "Scientists measure temperature, pressure and humidity all over the country.",
        "Those numbers travel through computers that compare them to past storms.",
        "Although the models are good, the atmosphere is enormous and restless.",
        "Small changes in one place can grow into large changes somewhere else.",
        "That is why a forecast for tomorrow is usually right, and one for next week often is not.",
      ]],
      ["Science: honeybees", ["colony", "nectar", "pollen", "hexagon", "survive"], ["through", "because", "several", "although", "eventually"], [
        "A honeybee colony can hold sixty thousand bees.",
        "Each one has a job, and the jobs change as the bee gets older.",
        "Young bees clean cells and feed the young.",
        "Older bees fly out for nectar and pollen.",
        "The wax cells they build are hexagons, because that shape wastes the least space.",
        "Although a single bee lives only a few weeks, the colony can survive for years.",
        "Eventually a new queen takes over, and the work continues.",
      ]],
      ["History: the first flight", ["invention", "experiment", "engine", "controls", "December"], ["although", "because", "through", "several", "finally"], [
        "Orville and Wilbur Wright owned a bicycle shop in Ohio.",
        "They spent several years testing wings before they built an engine.",
        "Most of their experiments failed, and some were dangerous.",
        "Although other people were trying too, the brothers solved a harder problem.",
        "They worked out how a pilot could steer, not just lift off.",
        "In December of 1903 the first flight lasted twelve seconds.",
        "Finally, a machine with a person in it had flown and landed under control.",
      ]],
    ]},
    { title: "Longer Words", weeks: [
      ["Three syllables", ["important", "remember", "together", "different", "wonderful"], ["although", "because", "through", "several", "eventually"], [
        "My piano teacher told me something I still remember.",
        "She said the important part is not playing the notes correctly.",
        "It is making them sound like they belong together.",
        "That is a different skill, and it takes much longer to learn.",
        "For months I practiced the same eight bars.",
        "Although it was dull, eventually something changed.",
        "The first time it came out right, it was wonderful.",
      ]],
      ["Four syllables", ["immediately", "information", "celebration", "especially", "unbelievable"], ["through", "because", "although", "several", "finally"], [
        "The news came through on a Tuesday afternoon.",
        "Our team had qualified for the state tournament.",
        "At first the information seemed unbelievable, especially to me.",
        "We had lost several games early in the season.",
        "Our coach immediately called a practice for that evening.",
        "Although we were tired, nobody missed it.",
        "The celebration came later, and it was worth the wait.",
      ]],
      ["Silent letters", ["knowledge", "wrestle", "whistle", "island", "answer"], ["because", "through", "although", "several", "eventually"], [
        "There is a small island in the middle of the lake.",
        "You can swim to it, although the water is cold.",
        "My cousins and I used to wrestle over who would go first.",
        "The answer was always the same: whoever could stand the cold longest.",
        "We would whistle from the island to show we had made it.",
        "That knowledge — that I could swim that far — stayed with me for years.",
      ]],
    ]},
    { title: "Ready for Third Grade", weeks: [
      ["Review: long words", ["community", "experience", "opportunity", "responsible", "independent"], ["although", "because", "through", "several", "eventually"], [
        "Our community center runs a garden every summer.",
        "Anyone can claim a plot, although you are responsible for your own weeds.",
        "I asked for one the year I turned nine.",
        "My mother said it was my opportunity to be independent.",
        "The first season was mostly a failure.",
        "Through trial and error I learned what my corner of the garden liked.",
        "Eventually I grew enough tomatoes to give some away.",
        "It is still the best experience I have had with my own two hands.",
      ]],
      ["Review: figurative language", ["blanket", "whispered", "swallowed", "danced", "crawled"], ["although", "because", "through", "several", "finally"], [
        "Fog crawled across the field just after dawn.",
        "It swallowed the fence posts one by one.",
        "A blanket of white lay over everything we knew by heart.",
        "The grass whispered when the wind pushed through it.",
        "Light danced along the top of the fog where the sun reached it.",
        "Although it looked like it would last all day, it was gone by nine.",
        "Finally the field was just a field again.",
      ]],
      ["Review: everything", ["accomplished", "determined", "challenging", "improvement", "confident"], ["because", "although", "through", "several", "eventually"], [
        "At the beginning of this year, reading a page out loud was challenging.",
        "I would stop in the middle of a sentence and lose my place.",
        "My teacher said the only fix was to read the same passage several times.",
        "That sounded dull, and for a while it was.",
        "But each time through, the words came a little faster.",
        "I was determined not to quit, although some days were hard.",
        "Looking back, the improvement is obvious.",
        "I feel confident now, and I accomplished that by reading it again and again.",
      ]],
    ]},
  ],
};
