import type { GradeDef } from "./types";

/** Grade 3: multisyllable words, affixes, content-area reading. 90–140 words. */
export const GRADE_3: GradeDef = {
  id: "3",
  label: "Grade 3",
  emoji: "3️⃣",
  color: "#8b5cf6",
  soft: "#f5f3ff",
  wcpm: { fall: 83, winter: 97, spring: 112 },
  units: [
    { title: "Syllable Patterns", weeks: [
      ["Closed syllables", ["napkin", "rabbit", "contest", "insect", "picnic"], ["through", "although", "several", "because", "eventually"], [
        "Every August our town holds a picnic in the park by the river.",
        "There is a contest for the best pie, and my grandmother has entered it nine times.",
        "She has never won, although everyone agrees her crust is the best.",
        "Last year a rabbit got into the tent before the judging started.",
        "It knocked over a stack of napkins and sent an entire table of insects scattering.",
        "By the time anyone caught it, three pies had been sampled without permission.",
        "My grandmother laughed harder than anyone.",
        "She said that eventually she will win, and until then she has a better story.",
      ]],
      ["Open syllables", ["music", "robot", "tiger", "paper", "pilot"], ["because", "through", "although", "several", "finally"], [
        "My uncle flew cargo planes for twenty-two years.",
        "He says a pilot spends most of the job waiting, and the rest paying attention.",
        "When I was small he let me hold the paper maps while he worked.",
        "They were covered in lines I could not read, although I pretended I could.",
        "He played music on the long stretches over open water.",
        "Once he told me that modern planes almost fly themselves, like a robot.",
        "Then he added that the robot has never once talked a nervous passenger down.",
        "Finally I understood why the waiting mattered.",
      ]],
      ["Vowel-consonant-e", ["escape", "complete", "surprise", "mistake", "explode"], ["although", "because", "several", "through", "eventually"], [
        "Our science fair project was supposed to be a simple volcano.",
        "My partner wanted it to explode higher than anyone else's.",
        "We added more baking soda than the instructions suggested, which was a mistake.",
        "During the test run, the mixture escaped down the side of the table.",
        "It took us several towels and most of an afternoon to clean up.",
        "On the day of the fair the volcano worked perfectly.",
        "Although we did not win, our teacher said it was the most complete write-up.",
        "The real surprise was how much we learned from the failed test.",
      ]],
    ]},
    { title: "Prefixes", weeks: [
      ["un- and dis-", ["uncomfortable", "disappear", "unexpected", "disagree", "unfamiliar"], ["although", "because", "several", "through", "eventually"], [
        "We moved to a new town the summer before third grade.",
        "Everything was unfamiliar, from the streets to the sound of the house at night.",
        "For weeks I was uncomfortable in a way I could not explain.",
        "I would disagree with my parents about things that did not matter.",
        "Then something unexpected happened at the park.",
        "A girl asked if I wanted to join her game, and I said yes without thinking.",
        "The strangeness did not disappear all at once.",
        "But eventually the new place stopped feeling new and started feeling like mine.",
      ]],
      ["re- and pre-", ["rearrange", "prepare", "rebuild", "preview", "rediscover"], ["because", "although", "several", "through", "finally"], [
        "My mother keeps a box of photographs she has never put into an album.",
        "Every few years she decides to prepare one and gets as far as sorting them.",
        "Then she will rearrange the piles, sit back, and look at a single picture for an hour.",
        "That is usually the end of the project.",
        "Last winter we finally did it together, over several evenings.",
        "She would preview each one before deciding where it belonged.",
        "Watching her rediscover people she had not thought about in years was the best part.",
        "The album is finished now, although she still keeps the box.",
      ]],
      ["mis-, non-, over-", ["misunderstand", "nonsense", "overlook", "mistaken", "overcome"], ["although", "because", "through", "several", "eventually"], [
        "People often misunderstand what a lighthouse keeper actually did.",
        "It was not simply a matter of turning on a light.",
        "The lens had to be cleaned daily, because even a thin film of salt would dim it.",
        "A keeper who overlooked that work put ships in real danger.",
        "The idea that it was a lonely, easy job is mostly nonsense.",
        "Many keepers were mistaken for hermits when they were actually highly trained.",
        "Although the work was hard, most of them loved it.",
        "Eventually machines took over, and the last keeper left her post in 1998.",
      ]],
    ]},
    { title: "Suffixes", weeks: [
      ["-tion and -sion", ["attention", "decision", "celebration", "direction", "permission"], ["although", "because", "several", "through", "eventually"], [
        "Our class was given permission to plan the end-of-year celebration ourselves.",
        "The first decision was the hardest: what kind of event it should be.",
        "Half the class wanted a field day and half wanted a talent show.",
        "Our teacher refused to break the tie, which got everyone's attention.",
        "She said learning to settle a disagreement was the point.",
        "After several long discussions we found a direction that worked.",
        "We held a field day in the morning and a talent show after lunch.",
        "Eventually both sides admitted the other half had been right too.",
      ]],
      ["-ly and -ness", ["carefully", "suddenly", "kindness", "darkness", "eventually"], ["although", "because", "through", "several", "finally"], [
        "Our power went out during an ice storm two winters ago.",
        "The darkness came suddenly, in the middle of dinner.",
        "My father carefully lit the candles he keeps in the hall closet.",
        "We ate the rest of the meal by candlelight, which my sister loved.",
        "A neighbor knocked an hour later to check on us.",
        "He brought extra blankets, although he barely knew our names.",
        "That kindness is the thing I remember, not the cold.",
        "Finally, after two days, the lights came back on at three in the morning.",
      ]],
      ["-able and -ment", ["comfortable", "measurement", "valuable", "movement", "remarkable"], ["because", "although", "several", "through", "eventually"], [
        "Building a canoe by hand takes most of a winter.",
        "My grandfather did it twice, and I watched the second time.",
        "Every measurement had to be checked, and then checked again.",
        "He said a mistake of half an inch would be visible for the life of the boat.",
        "The most remarkable part was the movement of the wood as it bent.",
        "Steam made it soft enough to curve without cracking.",
        "Although the finished canoe was not comfortable, it was beautiful.",
        "It is the single most valuable thing anyone in my family owns.",
      ]],
    ]},
    { title: "Reading Science", weeks: [
      ["The water cycle", ["evaporation", "condensation", "precipitation", "collection", "vapor"], ["although", "because", "through", "several", "eventually"], [
        "Every drop of water on Earth has been here for billions of years.",
        "It simply moves through the same cycle again and again.",
        "Heat from the sun causes evaporation, lifting water into the air as vapor.",
        "High above the ground the air is colder, and condensation turns the vapor back into droplets.",
        "Those droplets gather into clouds until they are too heavy to stay up.",
        "Then precipitation falls as rain, snow, sleet or hail.",
        "Collection happens when that water returns to rivers, lakes and oceans.",
        "Although the words are long, the idea is simple: the same water, going around forever.",
      ]],
      ["Animal migration", ["migration", "instinct", "navigate", "seasonal", "survival"], ["because", "although", "through", "several", "eventually"], [
        "Arctic terns make the longest migration of any animal on Earth.",
        "Each year they fly from the Arctic to Antarctica and back again.",
        "That round trip can cover forty thousand miles.",
        "Nobody taught them the route; they navigate by instinct, the sun and the stars.",
        "Young birds make the journey without their parents on the first try.",
        "Scientists believe the seasonal trip is about survival and food supply.",
        "By chasing summer in both hemispheres, a tern sees more daylight than any creature alive.",
        "Although it weighs about as much as a baseball, it may fly a million miles in its life.",
      ]],
      ["How bridges stand", ["suspension", "tension", "compression", "foundation", "engineer"], ["although", "because", "through", "several", "eventually"], [
        "Every bridge must solve the same problem: holding weight across empty space.",
        "An engineer does this by directing force into materials that can handle it.",
        "Compression squeezes a material, and tension stretches it.",
        "Stone is excellent under compression but fails under tension.",
        "Steel cable is the opposite, which is why a suspension bridge uses so much of it.",
        "The cables pull downward on towers that push that force into a deep foundation.",
        "Although the roadway looks like it is floating, it is held by thousands of smaller wires.",
        "Each one is thin enough to hold in your hand.",
      ]],
    ]},
    { title: "Reading History", weeks: [
      ["The Pony Express", ["express", "relay", "territory", "telegraph", "reliable"], ["although", "because", "through", "several", "eventually"], [
        "The Pony Express carried mail across two thousand miles of open territory.",
        "A single letter changed hands many times along a relay of stations.",
        "Riders were young, light, and willing to ride through weather and danger.",
        "A fresh horse waited every ten miles, and a fresh rider every seventy-five.",
        "The fastest run delivered a message in seven days and seventeen hours.",
        "Although it was remarkably reliable, the service lasted only eighteen months.",
        "The telegraph reached the west coast in October of 1861.",
        "Eventually a message that took a week could travel in minutes, and the riders were done.",
      ]],
      ["Ellis Island", ["immigrant", "inspection", "harbor", "document", "opportunity"], ["because", "although", "through", "several", "finally"], [
        "Between 1892 and 1954, twelve million people entered the United States through Ellis Island.",
        "Ships anchored in the harbor and passengers were ferried to the island in groups.",
        "The first stop was a medical inspection at the top of a long staircase.",
        "Doctors watched people climb, because a limp or heavy breathing could be seen from below.",
        "Next came questions and a check of every document.",
        "Most people were through in a matter of hours.",
        "Although about two percent were turned away, the vast majority walked out free.",
        "Finally they boarded ferries to the mainland and the opportunity they had crossed an ocean for.",
      ]],
      ["The library at Alexandria", ["scholar", "manuscript", "collection", "ancient", "preserve"], ["although", "because", "through", "several", "eventually"], [
        "The ancient library at Alexandria tried to collect every book in the world.",
        "Ships entering the harbor were searched, and any manuscript aboard was copied.",
        "Sometimes the library kept the original and returned the copy.",
        "Scholars came from across the Mediterranean to study the collection.",
        "They measured the Earth, mapped the stars, and argued about everything.",
        "Although stories say the library burned in a single night, the truth is slower and sadder.",
        "Funding dried up, scholars left, and the collection decayed over centuries.",
        "Eventually nothing remained, which is why so much ancient knowledge was never preserved.",
      ]],
    ]},
  ],
};
