import type { GradeDef } from "./types";

/** Grade 3: multisyllable words, affixes, content-area reading. 90–140 words. */
export const GRADE_3: GradeDef = {
  id: "3",
  label: "Grade 3",
  emoji: "3️⃣",
  color: "#8b5cf6",
  soft: "#f5f3ff",
  wcpm: { fall: 83, winter: 97, spring: 112 },
  units: [
    { title: "Syllable Patterns", weeks: [
      ["Closed syllables", ["napkin", "rabbit", "contest", "insect", "picnic"], ["through", "although", "several", "because", "eventually"], [
        "Every August our town holds a picnic in the park by the river.",
        "There is a contest for the best pie, and my grandmother has entered it nine times.",
        "She has never won, although everyone agrees her crust is the best.",
        "Last year a rabbit got into the tent before the judging started.",
        "It knocked over a stack of napkins and sent an entire table of insects scattering.",
        "By the time anyone caught it, three pies had been sampled without permission.",
        "My grandmother laughed harder than anyone.",
        "She said that eventually she will win, and until then she has a better story.",
      ]],
      ["Open syllables", ["music", "robot", "tiger", "paper", "pilot"], ["because", "through", "although", "several", "finally"], [
        "My uncle flew cargo planes for twenty-two years.",
        "He says a pilot spends most of the job waiting, and the rest paying attention.",
        "When I was small he let me hold the paper maps while he worked.",
        "They were covered in lines I could not read, although I pretended I could.",
        "He played music on the long stretches over open water.",
        "Once he told me that modern planes almost fly themselves, like a robot.",
        "Then he added that the robot has never once talked a nervous passenger down.",
        "Finally I understood why the waiting mattered.",
      ]],
      ["Vowel-consonant-e", ["escape", "complete", "surprise", "mistake", "explode"], ["although", "because", "several", "through", "eventually"], [
        "Our science fair project was supposed to be a simple volcano.",
        "My partner wanted it to explode higher than anyone else's.",
        "We added more baking soda than the instructions suggested, which was a mistake.",
        "During the test run, the mixture escaped down the side of the table.",
        "It took us several towels and most of an afternoon to clean up.",
        "On the day of the fair the volcano worked perfectly.",
        "Although we did not win, our teacher said it was the most complete write-up.",
        "The real surprise was how much we learned from the failed test.",
      ]],
    ]},
    { title: "Prefixes", weeks: [
      ["un- and dis-", ["uncomfortable", "disappear", "unexpected", "disagree", "unfamiliar"], ["although", "because", "several", "through", "eventually"], [
        "We moved to a new town the summer before third grade.",
        "Everything was unfamiliar, from the streets to the sound of the house at night.",
        "For weeks I was uncomfortable in a way I could not explain.",
        "I would disagree with my parents about things that did not matter.",
        "Then something unexpected happened at the park.",
        "A girl asked if I wanted to join her game, and I said yes without thinking.",
        "The strangeness did not disappear all at once.",
        "But eventually the new place stopped feeling new and started feeling like mine.",
      ]],
      ["re- and pre-", ["rearrange", "prepare", "rebuild", "preview", "rediscover"], ["because", "although", "several", "through", "finally"], [
        "My mother keeps a box of photographs she has never put into an album.",
        "Every few years she decides to prepare one and gets as far as sorting them.",
        "Then she will rearrange the piles, sit back, and look at a single picture for an hour.",
        "That is usually the end of the project.",
        "Last winter we finally did it together, over several evenings.",
        "She would preview each one before deciding where it belonged.",
        "Watching her rediscover people she had not thought about in years was the best part.",
        "The album is finished now, although she still keeps the box.",
      ]],
      ["mis-, non-, over-", ["misunderstand", "nonsense", "overlook", "mistaken", "overcome"], ["although", "because", "through", "several", "eventually"], [
        "People often misunderstand what a lighthouse keeper actually did.",
        "It was not simply a matter of turning on a light.",
        "The lens had to be cleaned daily, because even a thin film of salt would dim it.",
        "A keeper who overlooked that work put ships in real danger.",
        "The idea that it was a lonely, easy job is mostly nonsense.",
        "Many keepers were mistaken for hermits when they were actually highly trained.",
        "Although the work was hard, most of them loved it.",
        "Eventually machines took over, and the last keeper left her post in 1998.",
      ]],
    ]},
    { title: "Suffixes", weeks: [
      ["-tion and -sion", ["attention", "decision", "celebration", "direction", "permission"], ["although", "because", "several", "through", "eventually"], [
        "Our class was given permission to plan the end-of-year celebration ourselves.",
        "The first decision was the hardest: what kind of event it should be.",
        "Half the class wanted a field day and half wanted a talent show.",
        "Our teacher refused to break the tie, which got everyone's attention.",
        "She said learning to settle a disagreement was the point.",
        "After several long discussions we found a direction that worked.",
        "We held a field day in the morning and a talent show after lunch.",
        "Eventually both sides admitted the other half had been right too.",
      ]],
      ["-ly and -ness", ["carefully", "suddenly", "kindness", "darkness", "eventually"], ["although", "because", "through", "several", "finally"], [
        "Our power went out during an ice storm two winters ago.",
        "The darkness came suddenly, in the middle of dinner.",
        "My father carefully lit the candles he keeps in the hall closet.",
        "We ate the rest of the meal by candlelight, which my sister loved.",
        "A neighbor knocked an hour later to check on us.",
        "He brought extra blankets, although he barely knew our names.",
        "That kindness is the thing I remember, not the cold.",
        "Finally, after two days, the lights came back on at three in the morning.",
      ]],
      ["-able and -ment", ["comfortable", "measurement", "valuable", "movement", "remarkable"], ["because", "although", "several", "through", "eventually"], [
        "Building a canoe by hand takes most of a winter.",
        "My grandfather did it twice, and I watched the second time.",
        "Every measurement had to be checked, and then checked again.",
        "He said a mistake of half an inch would be visible for the life of the boat.",
        "The most remarkable part was the movement of the wood as it bent.",
        "Steam made it soft enough to curve without cracking.",
        "Although the finished canoe was not comfortable, it was beautiful.",
        "It is the single most valuable thing anyone in my family owns.",
      ]],
    ]},
    { title: "Reading Science", weeks: [
      ["The water cycle", ["evaporation", "condensation", "precipitation", "collection", "vapor"], ["although", "because", "through", "several", "eventually"], [
        "Every drop of water on Earth has been here for billions of years.",
        "It simply moves through the same cycle again and again.",
        "Heat from the sun causes evaporation, lifting water into the air as vapor.",
        "High above the ground the air is colder, and condensation turns the vapor back into droplets.",
        "Those droplets gather into clouds until they are too heavy to stay up.",
        "Then precipitation falls as rain, snow, sleet or hail.",
        "Collection happens when that water returns to rivers, lakes and oceans.",
        "Although the words are long, the idea is simple: the same water, going around forever.",
      ]],
      ["Animal migration", ["migration", "instinct", "navigate", "seasonal", "survival"], ["because", "although", "through", "several", "eventually"], [
        "Arctic terns make the longest migration of any animal on Earth.",
        "Each year they fly from the Arctic to Antarctica and back again.",
        "That round trip can cover forty thousand miles.",
        "Nobody taught them the route; they navigate by instinct, the sun and the stars.",
        "Young birds make the journey without their parents on the first try.",
        "Scientists believe the seasonal trip is about survival and food supply.",
        "By chasing summer in both hemispheres, a tern sees more daylight than any creature alive.",
        "Although it weighs about as much as a baseball, it may fly a million miles in its life.",
      ]],
      ["How bridges stand", ["suspension", "tension", "compression", "foundation", "engineer"], ["although", "because", "through", "several", "eventually"], [
        "Every bridge must solve the same problem: holding weight across empty space.",
        "An engineer does this by directing force into materials that can handle it.",
        "Compression squeezes a material, and tension stretches it.",
        "Stone is excellent under compression but fails under tension.",
        "Steel cable is the opposite, which is why a suspension bridge uses so much of it.",
        "The cables pull downward on towers that push that force into a deep foundation.",
        "Although the roadway looks like it is floating, it is held by thousands of smaller wires.",
        "Each one is thin enough to hold in your hand.",
      ]],
    ]},
    { title: "Reading History", weeks: [
      ["The Pony Express", ["express", "relay", "territory", "telegraph", "reliable"], ["although", "because", "through", "several", "eventually"], [
        "The Pony Express carried mail across two thousand miles of open territory.",
        "A single letter changed hands many times along a relay of stations.",
        "Riders were young, light, and willing to ride through weather and danger.",
        "A fresh horse waited every ten miles, and a fresh rider every seventy-five.",
        "The fastest run delivered a message in seven days and seventeen hours.",
        "Although it was remarkably reliable, the service lasted only eighteen months.",
        "The telegraph reached the west coast in October of 1861.",
        "Eventually a message that took a week could travel in minutes, and the riders were done.",
      ]],
      ["Ellis Island", ["immigrant", "inspection", "harbor", "document", "opportunity"], ["because", "although", "through", "several", "finally"], [
        "Between 1892 and 1954, twelve million people entered the United States through Ellis Island.",
        "Ships anchored in the harbor and passengers were ferried to the island in groups.",
        "The first stop was a medical inspection at the top of a long staircase.",
        "Doctors watched people climb, because a limp or heavy breathing could be seen from below.",
        "Next came questions and a check of every document.",
        "Most people were through in a matter of hours.",
        "Although about two percent were turned away, the vast majority walked out free.",
        "Finally they boarded ferries to the mainland and the opportunity they had crossed an ocean for.",
      ]],
      ["The library at Alexandria", ["scholar", "manuscript", "collection", "ancient", "preserve"], ["although", "because", "through", "several", "eventually"], [
        "The ancient library at Alexandria tried to collect every book in the world.",
        "Ships entering the harbor were searched, and any manuscript aboard was copied.",
        "Sometimes the library kept the original and returned the copy.",
        "Scholars came from across the Mediterranean to study the collection.",
        "They measured the Earth, mapped the stars, and argued about everything.",
        "Although stories say the library burned in a single night, the truth is slower and sadder.",
        "Funding dried up, scholars left, and the collection decayed over centuries.",
        "Eventually nothing remained, which is why so much ancient knowledge was never preserved.",
      ]],
    ]},
    { title: "Big Words, Long Vowels", weeks: [
      ["Vowel teams in long words", ["remainder", "complaining", "repeating", "explaining", "containing"], ["although", "because", "through", "several", "eventually"], [
        "My piano teacher gave me a piece with a repeating pattern in the left hand.",
        "For three weeks I kept complaining that it was boring.",
        "She listened without explaining why she had chosen it.",
        "Then one afternoon she sat down and played the whole thing properly.",
        "The repeating part was not the point; it was the floor everything else stood on.",
        "Once I understood that, the remainder of the piece came quickly.",
        "Eventually I played it for my grandparents at Christmas.",
        "My teacher never said she had been right, although we both knew it.",
      ]],
      ["Open and closed syllables", ["hotel", "robot", "silent", "pilot", "frozen"], ["because", "although", "through", "several", "finally"], [
        "The lake behind our cabin stays frozen until the middle of April.",
        "In January the whole valley goes silent, the way only deep cold can make it.",
        "My father grew up here, and he still points out the old hotel on the far shore.",
        "It closed before I was born, although the sign is somehow still standing.",
        "One winter a small plane landed on the ice, and the pilot waved at us.",
        "My brother said it looked like a toy, or a robot from a film.",
        "Finally the ice groans and cracks, and the valley gets loud again.",
      ]],
      ["Schwa, the lazy vowel", ["banana", "problem", "pencil", "wagon", "circus"], ["although", "because", "several", "through", "eventually"], [
        "There is a vowel sound in English that has no letter of its own.",
        "Say banana out loud and listen to the first and last syllables.",
        "Neither one sounds like the letter a is supposed to sound.",
        "That lazy uh is called the schwa, and it turns up everywhere.",
        "The e in problem, the i in pencil, the o in wagon and the u in circus are all schwa.",
        "This is why so many words are hard to spell.",
        "You cannot hear which letter it is, because every unstressed vowel collapses into the same sound.",
        "Eventually you learn the spellings by sight, and the schwa stops being a problem.",
      ]],
    ]},
    { title: "Reading Geography", weeks: [
      ["Rivers and deltas", ["sediment", "channel", "delta", "fertile", "floodplain"], ["although", "because", "through", "several", "eventually"], [
        "A river carries more than water; it carries sediment picked up along the way.",
        "When the river slows, it drops that load, because slow water cannot hold heavy particles.",
        "Near the sea the current almost stops, and the sediment piles up.",
        "The river splits into several smaller channels to find its way through.",
        "That fan-shaped pile of land is called a delta.",
        "Delta soil is extremely fertile, which is why people have farmed river mouths for thousands of years.",
        "The Nile delta fed ancient Egypt for three millennia.",
        "Although floods were dangerous, they were also what renewed the soil each year.",
      ]],
      ["Mountains and weather", ["elevation", "moisture", "windward", "desert", "barrier"], ["because", "although", "through", "several", "eventually"], [
        "Mountains make their own weather, and they do it in a way you can predict.",
        "Wind carrying moisture from the ocean hits the mountain and has nowhere to go but up.",
        "As the air rises it cools, and cool air cannot hold as much water.",
        "The moisture falls as rain on the windward side, which stays green and lush.",
        "By the time the air crosses the peak, it has very little water left.",
        "Coming down the other side it warms again and soaks up what moisture remains.",
        "Consequently the far side is dry, and sometimes a desert.",
        "This is called a rain shadow, and it explains why one side of a mountain can be a rainforest and the other a wasteland.",
      ]],
      ["Reading a map", ["legend", "compass", "scale", "boundary", "symbol"], ["although", "because", "through", "several", "eventually"], [
        "Every map is a small lie told to make something enormous fit on paper.",
        "The legend tells you which lie you are reading: what each symbol stands for.",
        "A thick red line might be a highway on one map and a boundary on another.",
        "The scale tells you how much shrinking has happened.",
        "On a scale of one to one hundred thousand, one inch of paper equals about a mile and a half.",
        "The compass rose tells you which way is north, although north is not always at the top.",
        "Old maps sometimes put east at the top, because that is where the sun rises.",
        "Once you can read a legend, a scale and a compass, you can read any map ever drawn.",
      ]],
    ]},
    { title: "Figurative Language", weeks: [
      ["Similes and metaphors", ["comparison", "describe", "vivid", "imagine", "ordinary"], ["although", "because", "through", "several", "eventually"], [
        "Writers use comparison to make you see something you have never seen.",
        "A simile says one thing is like another: the fog came in like a grey tide.",
        "A metaphor goes further and says one thing is another: the fog was a grey tide.",
        "The metaphor is stronger, because it does not pause to admit the comparison.",
        "Both work by borrowing something ordinary to describe something unfamiliar.",
        "You already know what a tide looks like, so the writer does not have to explain the fog.",
        "The best comparisons are surprising but immediately right.",
        "A tired comparison, like quiet as a mouse, has been used so often that you stop seeing anything at all.",
      ]],
      ["Idioms", ["expression", "literal", "meaning", "confusing", "familiar"], ["although", "because", "through", "several", "eventually"], [
        "An idiom is a phrase whose meaning has nothing to do with its words.",
        "If someone says it is raining cats and dogs, no animals are involved.",
        "English is full of these, and they are confusing for anyone learning the language.",
        "To let the cat out of the bag means to reveal a secret.",
        "To bite off more than you can chew means to take on too much.",
        "The literal meaning is useless; you simply have to know the expression.",
        "Most idioms started as something concrete and then drifted.",
        "Eventually everyone forgot the original picture, and only the meaning survived.",
      ]],
      ["Personification", ["personify", "describe", "human", "powerful", "lifeless"], ["although", "because", "through", "several", "eventually"], [
        "Personification gives human qualities to things that are not alive.",
        "The wind howled, the floorboards complained, the sun refused to come out.",
        "None of those things can howl or complain or refuse, and yet the sentences make sense instantly.",
        "This works because people are extremely good at reading other people.",
        "Borrowing that skill makes a lifeless thing feel immediate and important.",
        "It is also why weather in stories so often matches the mood of the characters.",
        "A storm that rages while someone is furious is doing double duty.",
        "Although it is a simple trick, it is one of the most powerful in all of writing.",
      ]],
    ]},
    { title: "Reading About People", weeks: [
      ["Jane Goodall", ["observe", "patient", "chimpanzee", "behavior", "discovery"], ["although", "because", "through", "several", "eventually"], [
        "In 1960 a young woman with no university degree went to Tanzania to watch chimpanzees.",
        "Scientists at the time believed you should study animals as numbers, not individuals.",
        "Jane Goodall gave hers names instead, which other researchers thought was unserious.",
        "For months the chimpanzees fled whenever she appeared.",
        "She simply kept showing up, sitting at a distance, being patient.",
        "Eventually one of them, David Greybeard, let her come close.",
        "She watched him strip leaves from a twig and use it to fish termites out of a mound.",
        "Until that moment, scientists believed only humans made tools.",
        "That single observation changed the definition of what a human being is.",
      ]],
      ["Wilma Rudolph", ["determined", "recover", "champion", "impossible", "competition"], ["because", "although", "through", "several", "eventually"], [
        "Wilma Rudolph was the twentieth of twenty-two children, born early and very small.",
        "At four she caught polio and lost the use of her left leg.",
        "Doctors said she would never walk normally again.",
        "Her mother drove her ninety miles each way for treatment, twice a week, for years.",
        "Her brothers and sisters took turns massaging the leg every single day.",
        "By nine she could walk with a brace, and by twelve she had thrown it away.",
        "In 1960 she won three gold medals at the Olympic Games in Rome.",
        "Eventually she was called the fastest woman in the world.",
        "She always said the real work had happened in her family's front room.",
      ]],
      ["Jacques Cousteau", ["ocean", "equipment", "explore", "underwater", "documentary"], ["although", "because", "through", "several", "eventually"], [
        "Before 1943, a diver could not go deep or stay down for long.",
        "Air came through a hose from a boat above, which meant the diver was tethered.",
        "Jacques Cousteau and an engineer named Emile Gagnan solved the problem.",
        "They built a valve that delivered air at exactly the pressure of the surrounding water.",
        "A diver could now carry tanks and swim freely, which changed everything.",
        "Cousteau then did something nobody expected: he brought cameras.",
        "His documentaries showed millions of people a world they had no idea existed.",
        "Although he began as an explorer, he spent his later life as a conservationist.",
        "He said people protect only what they love, and they love only what they have seen.",
      ]],
    ]},
    { title: "Ready for Fourth Grade", weeks: [
      ["Review: word parts", ["unbelievable", "disagreement", "transportation", "comfortable", "information"], ["although", "because", "through", "several", "eventually"], [
        "By now a long word should look like a set of pieces rather than a wall.",
        "Transportation is trans, port and ation: the act of carrying across.",
        "Disagreement is dis, agree and ment: the state of not agreeing.",
        "Unbelievable is un, believe and able: not able to be believed.",
        "None of those required a dictionary.",
        "This is the skill that makes the next few years of school possible.",
        "Every subject you take will arrive with its own pile of long words.",
        "Eventually you will meet thousands of them, and nobody will have time to teach you each one.",
      ]],
      ["Review: reading for meaning", ["summarize", "predict", "question", "connect", "visualize"], ["although", "because", "through", "several", "eventually"], [
        "Good readers do several things at once without noticing.",
        "They predict what is coming, and they notice when they were wrong.",
        "They ask questions as they go, even silly ones.",
        "They picture what is being described, which is why a boring passage often means you stopped visualizing.",
        "They connect new information to something they already know.",
        "And at the end of each section, they summarize it to themselves in a sentence.",
        "If the sentence will not come, the understanding is not there yet.",
        "Although this sounds like a lot of work, it becomes automatic with practice.",
      ]],
      ["Review: everything", ["fluency", "practice", "progress", "confident", "achievement"], ["although", "because", "through", "several", "eventually"], [
        "Think about where you were at the start of third grade.",
        "Long words made you stop, and stopping made you lose the thread of the sentence.",
        "Now you take those same words apart without thinking about it.",
        "That did not happen because somebody taught you every word.",
        "It happened because you read, and reread, and kept going when it was dull.",
        "Fluency is simply the point where the decoding becomes invisible.",
        "Once it is invisible, all of your attention is free for the meaning.",
        "That is the whole achievement, and it is yours.",
        "Fourth grade will hand you harder books, and you are ready for them.",
      ]],
    ]},
  ],
};
