import type { GradeDef } from "./types";

/** Grade 4: Greek and Latin roots, content-area reading. 120–170 words. */
export const GRADE_4: GradeDef = {
  id: "4",
  label: "Grade 4",
  emoji: "4️⃣",
  color: "#10b981",
  soft: "#ecfdf5",
  wcpm: { fall: 94, winter: 120, spring: 133 },
  units: [
    { title: "Word Roots", weeks: [
      ["Roots: port, dict, scrib", ["transport", "predict", "describe", "import", "dictate"], ["although", "because", "through", "consequently", "furthermore"], [
        "Many English words are built from Latin pieces that still carry their old meanings.",
        "The root port means to carry, which is why we transport goods and import food.",
        "A passport carries you across a border, and a porter carries your bags.",
        "The root dict means to say or speak.",
        "When you predict something, you are saying it before it happens.",
        "A dictator is someone whose word becomes law, and to dictate is to speak aloud for someone else to write down.",
        "The root scrib or script means to write.",
        "You describe something by writing it down in words, and a prescription is written by a doctor.",
        "Once you know a handful of roots, unfamiliar words stop looking like nonsense.",
        "You can take them apart and make a reasonable guess at the meaning.",
      ]],
      ["Roots: spect, struct, tract", ["inspect", "construct", "attract", "spectator", "subtract"], ["although", "furthermore", "consequently", "therefore", "nevertheless"], [
        "The root spect means to look, and it hides inside a surprising number of words.",
        "A spectator looks on at a game, and an inspector looks closely at a building.",
        "When something is spectacular, it is worth looking at.",
        "The root struct means to build.",
        "You construct a model, destroy a sandcastle, and study the structure of a sentence.",
        "Instructions are the pieces of information built up to guide you.",
        "The root tract means to pull or drag.",
        "A tractor pulls a plow, a magnet attracts metal, and when you subtract you pull a number away.",
        "Nevertheless, roots are not a perfect system.",
        "English borrowed words from dozens of languages, and some of them simply do not break apart.",
      ]],
      ["Greek roots", ["telescope", "biography", "photograph", "geography", "microscope"], ["although", "therefore", "furthermore", "consequently", "nevertheless"], [
        "Greek roots cluster around science and learning, because Greek scholars named so much of it.",
        "Tele means far, and scope means to look, so a telescope looks far away.",
        "Micro means small, which makes a microscope a tool for looking at small things.",
        "Bio means life and graph means writing, so a biography is a written life.",
        "Photo means light, and therefore a photograph is written with light.",
        "Geo means earth, so geography is writing about the earth and geology is the study of it.",
        "Thermo means heat, which explains the thermometer and the thermos.",
        "Furthermore, these pieces combine freely.",
        "A word nobody has ever used, like photobiology, is still readable the first time you see it.",
      ]],
    ]},
    { title: "Reading Science", weeks: [
      ["Earthquakes", ["tectonic", "fault", "seismic", "magnitude", "epicenter"], ["although", "because", "therefore", "consequently", "nevertheless"], [
        "The outer shell of the Earth is broken into enormous tectonic plates.",
        "They float on hotter rock below and grind slowly past one another.",
        "Where two plates meet, the boundary is called a fault.",
        "The rock along a fault does not slide smoothly; friction locks it in place.",
        "Stress builds for years or centuries until the rock finally gives way.",
        "That sudden release sends seismic waves outward in every direction.",
        "The point underground where the break begins is the focus, and the spot directly above it on the surface is the epicenter.",
        "Magnitude measures the energy released, and each whole number is about thirty-two times more energy than the one below it.",
        "Therefore a magnitude seven earthquake is not slightly worse than a six.",
        "It releases roughly thirty-two times as much energy.",
      ]],
      ["The human heart", ["circulation", "ventricle", "artery", "oxygen", "contract"], ["although", "because", "therefore", "furthermore", "consequently"], [
        "Your heart is a muscle about the size of your fist, and it never rests.",
        "It beats roughly one hundred thousand times a day without being told to.",
        "The heart has four chambers: two atria on top and two ventricles below.",
        "Blood returning from the body is low in oxygen and enters the right side.",
        "The right ventricle contracts and pushes that blood to the lungs.",
        "There it drops off carbon dioxide and picks up fresh oxygen.",
        "The blood returns to the left side, and the left ventricle sends it out through the largest artery in the body.",
        "Because that chamber has to reach your toes and your brain, its walls are the thickest.",
        "The whole circuit takes under a minute.",
        "Furthermore, a single drop of blood will make that trip thousands of times.",
      ]],
      ["Volcanoes", ["magma", "eruption", "pressure", "dormant", "crater"], ["although", "because", "therefore", "consequently", "nevertheless"], [
        "Deep below the surface, rock is hot enough to melt into magma.",
        "Magma is lighter than the solid rock around it, so it rises slowly.",
        "As it rises, dissolved gases come out of solution, the way bubbles appear when you open a bottle.",
        "Those gases build pressure, and pressure is what makes an eruption violent.",
        "Runny magma lets gas escape gently, producing the slow lava flows of Hawaii.",
        "Thick, sticky magma traps the gas until it explodes, as it did at Mount St. Helens.",
        "Once magma reaches the surface it is called lava.",
        "A volcano that has not erupted recently but could again is called dormant, not extinct.",
        "Nevertheless, dormant does not mean safe.",
        "Some of the most destructive eruptions in history came from mountains nobody expected to wake up.",
      ]],
    ]},
    { title: "Reading History", weeks: [
      ["The Silk Road", ["caravan", "merchant", "exchange", "route", "civilization"], ["although", "because", "therefore", "furthermore", "consequently"], [
        "The Silk Road was never a single road, and silk was only part of what moved along it.",
        "It was a web of routes connecting China to the Mediterranean, stretching four thousand miles.",
        "Very few merchants traveled the whole distance.",
        "Instead, goods changed hands dozens of times, and the price climbed at every exchange.",
        "Caravans carried silk and porcelain west, and glass, wool and horses east.",
        "Along with goods traveled something far more important: ideas.",
        "Paper, gunpowder and the printing press all moved west along these routes.",
        "Religions, mathematics and astronomy traveled in both directions.",
        "Consequently, civilizations that never met face to face still shaped one another deeply.",
        "The routes also carried disease, including the plague that reshaped Europe in the fourteenth century.",
      ]],
      ["The printing press", ["movable", "manuscript", "literacy", "revolution", "distribute"], ["although", "because", "therefore", "furthermore", "nevertheless"], [
        "Before the printing press, every book in Europe was copied by hand.",
        "A single manuscript could take a skilled scribe more than a year.",
        "Books were therefore rare, expensive, and owned mostly by churches and the wealthy.",
        "Around 1440 Johannes Gutenberg combined several existing ideas into one machine.",
        "His key contribution was movable metal type that could be rearranged and reused.",
        "A page could be set once and printed hundreds of times.",
        "Within fifty years there were presses in more than two hundred European cities.",
        "The price of a book fell sharply, and literacy began to climb.",
        "Nevertheless, the revolution was not only about cost.",
        "For the first time, two people in different countries could read exactly the same words, with no copying errors between them.",
      ]],
      ["Mapping the world", ["longitude", "latitude", "navigation", "chronometer", "accurate"], ["although", "because", "therefore", "consequently", "furthermore"], [
        "For centuries sailors could find their latitude easily but not their longitude.",
        "Latitude is how far north or south you are, and the sun and stars give it away.",
        "Longitude is how far east or west, and nothing in the sky answers that directly.",
        "The solution turned out to be a clock.",
        "If you know the exact time at a fixed place and compare it to local noon, the difference gives your longitude.",
        "The problem was that no clock could keep accurate time on a rolling, salty ship.",
        "John Harrison, a carpenter with no formal training, spent forty years solving it.",
        "His fourth chronometer lost only five seconds on a voyage to Jamaica.",
        "Consequently, navigation became a matter of arithmetic rather than guesswork.",
        "Countless lives were saved by a box of gears.",
      ]],
    ]},
    { title: "Reading Closely", weeks: [
      ["Author's purpose", ["persuade", "inform", "entertain", "evidence", "opinion"], ["although", "because", "therefore", "furthermore", "nevertheless"], [
        "Every piece of writing is trying to do something to you.",
        "Most writing aims to inform, to persuade, or to entertain, and often more than one at once.",
        "Learning to tell them apart changes how you read.",
        "A text that informs sticks mostly to facts that can be checked.",
        "A text that persuades selects its facts, and the selection is the argument.",
        "Watch for words that carry feeling rather than information.",
        "A road described as narrow is informing you; a road described as treacherous is persuading you.",
        "Neither is dishonest, but they are doing different work.",
        "Furthermore, the strongest persuasion rarely announces itself.",
        "It arrives dressed as a simple account of what happened.",
      ]],
      ["Fact and opinion", ["verify", "claim", "support", "reliable", "source"], ["although", "because", "therefore", "consequently", "nevertheless"], [
        "A fact is a claim that can be checked against the world.",
        "An opinion is a judgment, and reasonable people can hold different ones.",
        "The tricky part is that opinions often wear the clothing of facts.",
        "The sentence this is the best museum in the state sounds factual but cannot be verified.",
        "The sentence this museum had more visitors than any other last year can be.",
        "When you meet a claim, ask what would have to be true for it to be false.",
        "If you cannot imagine such evidence, you are probably looking at an opinion.",
        "Then ask where the claim came from.",
        "A reliable source names its evidence and tells you how it was gathered.",
        "Nevertheless, even careful sources make mistakes, which is why two independent sources beat one.",
      ]],
      ["Comparing accounts", ["perspective", "primary", "secondary", "witness", "interpret"], ["although", "because", "therefore", "furthermore", "consequently"], [
        "Historians distinguish between primary and secondary sources.",
        "A primary source comes from someone who was there: a letter, a photograph, a court record.",
        "A secondary source is written later by someone studying those materials.",
        "Both are useful, and both have limits.",
        "A witness saw only part of the event, from one position, through their own expectations.",
        "Two honest people at the same event will produce two different accounts.",
        "That is not evidence that one of them is lying.",
        "Historians therefore read many accounts and look for where they agree.",
        "Furthermore, they pay attention to what every account leaves out.",
        "Silence in the record often says as much as the words that survived.",
      ]],
    ]},
    { title: "Ready for Fifth Grade", weeks: [
      ["Review: roots and affixes", ["constructive", "interrupting", "transportation", "unpredictable", "autobiography"], ["although", "nevertheless", "consequently", "furthermore", "therefore"], [
        "By now you can take apart a word you have never seen.",
        "Autobiography breaks into auto, bio and graph: self, life, writing.",
        "Transportation contains trans and port: carrying across.",
        "Interrupting holds inter and rupt: to break between.",
        "Unpredictable is un, pre, dict and able: not able to be said beforehand.",
        "None of these required you to look anything up.",
        "This is the single most useful reading skill you will build this year.",
        "Vocabulary stops being a list to memorize and becomes a system to decode.",
        "Consequently, the number of words available to you grows far faster than anyone could teach them.",
      ]],
      ["Review: reading for information", ["summarize", "conclude", "analyze", "significant", "relationship"], ["although", "therefore", "furthermore", "consequently", "nevertheless"], [
        "Reading to learn is different from reading for pleasure, and it is a skill you practice.",
        "Start by looking at the headings and pictures before reading a word of the text.",
        "That gives your brain a frame to hang new information on.",
        "As you read, pause at the end of each section and summarize it in one sentence.",
        "If you cannot, you did not understand it, and rereading now is cheaper than rereading later.",
        "Look for the relationship between ideas, not just the ideas themselves.",
        "Did one thing cause another, or did they simply happen near each other?",
        "That distinction is the most significant one in all of nonfiction.",
        "Nevertheless, none of this works if you are reading too fast to notice.",
      ]],
      ["Review: everything", ["persistence", "comprehension", "deliberate", "fluency", "accomplishment"], ["although", "therefore", "consequently", "furthermore", "nevertheless"], [
        "Fluency is not the same thing as speed, although speed is part of it.",
        "A fluent reader decodes words so automatically that attention is free for meaning.",
        "That is why rereading the same passage three times works so well.",
        "The first read is decoding, the second is phrasing, and the third is understanding.",
        "Comprehension improves not because you memorized the passage but because your brain stopped spending effort on the words.",
        "This is deliberate practice, and it is the same thing a musician does with a difficult measure.",
        "Furthermore, the effect transfers.",
        "The fluency you build on one passage makes the next one easier.",
        "Persistence is the whole method, and the accomplishment is real.",
      ]],
    ]},
  ],
};

/** Grade 5: dense informational text, abstract vocabulary. 140–190 words. */
export const GRADE_5: GradeDef = {
  id: "5",
  label: "Grade 5",
  emoji: "5️⃣",
  color: "#f43f5e",
  soft: "#fff1f2",
  wcpm: { fall: 121, winter: 133, spring: 146 },
  units: [
    { title: "Academic Vocabulary", weeks: [
      ["Words about thinking", ["hypothesis", "assumption", "inference", "conclusion", "evidence"], ["although", "whereas", "consequently", "nevertheless", "furthermore"], [
        "Scientists use a vocabulary that sounds formal but describes ordinary mental moves.",
        "An assumption is something you treat as true without checking it.",
        "Everyone makes assumptions constantly; the danger lies in not knowing which ones you have made.",
        "A hypothesis is a proposed explanation that could turn out to be wrong.",
        "That last part matters enormously.",
        "If no possible observation could contradict your idea, it is not a hypothesis.",
        "An inference is a conclusion drawn from evidence rather than observed directly.",
        "You infer that it rained overnight from wet pavement in the morning.",
        "Whereas an observation is what you saw, an inference is what you concluded.",
        "Confusing the two is the most common error in scientific writing.",
        "Nevertheless, inference is unavoidable and often correct.",
        "The goal is not to stop inferring but to label it honestly when you do.",
      ]],
      ["Words about argument", ["counterargument", "concede", "refute", "valid", "assertion"], ["although", "whereas", "consequently", "furthermore", "nevertheless"], [
        "A strong argument does something that feels uncomfortable: it states the other side fairly.",
        "This is called addressing the counterargument, and skipping it weakens your case.",
        "Readers who already disagree with you will think of the objection anyway.",
        "If you have not mentioned it, they conclude you did not know about it.",
        "Sometimes the right move is to concede a point.",
        "Admitting that your opponent is correct about one thing makes your other claims more believable, not less.",
        "To refute a claim is to show it is false, which requires evidence rather than volume.",
        "A valid argument is one whose conclusion follows from its premises.",
        "Notice that a valid argument can still be wrong.",
        "If the premises are false, perfect logic will carry you straight to a false conclusion.",
        "Furthermore, most real disagreements are not about logic at all.",
        "They are about which facts matter most, which is a harder thing to settle.",
      ]],
      ["Words about systems", ["interdependent", "equilibrium", "feedback", "variable", "stability"], ["whereas", "although", "consequently", "nevertheless", "furthermore"], [
        "A system is a set of parts whose behavior depends on one another.",
        "The parts are interdependent, which means you cannot understand one by studying it alone.",
        "Feedback is what happens when the output of a system loops back as an input.",
        "Negative feedback pushes a system back toward balance, like a thermostat.",
        "When a room cools, the heater runs; when it warms, the heater stops.",
        "That balance point is called equilibrium, and it produces stability.",
        "Positive feedback does the opposite: it amplifies a change.",
        "Ice reflects sunlight, so melting ice means less reflection, which means more warming and more melting.",
        "Consequently, systems with strong positive feedback can shift suddenly rather than gradually.",
        "A variable is anything in the system that can change.",
        "Furthermore, changing one variable almost never changes only one thing.",
        "That is the central difficulty, and the central interest, of studying any system at all.",
      ]],
    ]},
    { title: "Reading Science", weeks: [
      ["Antibiotic resistance", ["bacteria", "resistance", "mutation", "selection", "prescribe"], ["although", "whereas", "consequently", "nevertheless", "furthermore"], [
        "When Alexander Fleming accepted his Nobel Prize in 1945, he issued a warning.",
        "He said that bacteria could become resistant to penicillin, and that careless use would make it happen faster.",
        "He was right, and the mechanism is straightforward.",
        "Bacteria reproduce enormously fast, and copying mistakes called mutations occur constantly.",
        "Most mutations are useless or harmful, but occasionally one lets a bacterium survive a drug.",
        "If you take an antibiotic and stop early, you kill the weakest bacteria and leave the toughest alive.",
        "Those survivors reproduce without competition.",
        "This is natural selection operating on a timescale of days rather than millennia.",
        "Consequently, the problem is not that bacteria are becoming cleverer.",
        "It is that we keep running the experiment that selects for resistance.",
        "Doctors now prescribe antibiotics more carefully, and finishing the full course matters more than most people realize.",
        "Nevertheless, some infections that were routinely curable in 1980 are becoming difficult to treat again.",
      ]],
      ["Plate tectonics", ["continental", "subduction", "ridge", "convection", "geological"], ["although", "whereas", "consequently", "furthermore", "nevertheless"], [
        "In 1912 Alfred Wegener noticed that the coastlines of South America and Africa fit together.",
        "He proposed that the continents had once been joined and had drifted apart.",
        "Geologists rejected the idea for almost fifty years, and for a defensible reason.",
        "Wegener could not explain what force could possibly move a continent.",
        "The answer arrived in the 1960s from the ocean floor.",
        "Mapping revealed a ridge running down the middle of the Atlantic where new crust is created.",
        "Rock gets older in both directions as you move away from it.",
        "The Atlantic is spreading, roughly as fast as your fingernails grow.",
        "Convection in the hot mantle below drives the motion.",
        "Where plates collide, one slides beneath the other in a process called subduction.",
        "Consequently, the deepest ocean trenches and the tallest mountains are produced by the same mechanism.",
        "Wegener died on an expedition in Greenland in 1930, thirty years before he was proved right.",
      ]],
      ["Light and color", ["spectrum", "wavelength", "absorb", "reflect", "perception"], ["whereas", "although", "consequently", "furthermore", "nevertheless"], [
        "Objects do not have color in the way they have mass.",
        "What an object has is a tendency to absorb some wavelengths of light and reflect others.",
        "A leaf absorbs most red and blue light and reflects green, which is why it looks green to you.",
        "In complete darkness the leaf has no color at all.",
        "White light contains the entire visible spectrum mixed together.",
        "A prism separates it because different wavelengths bend by different amounts as they pass through glass.",
        "Your eye contains three kinds of cone cells, sensitive to roughly red, green and blue.",
        "Every color you have ever seen is your brain comparing the signals from those three.",
        "Consequently, color is partly a property of the world and partly a construction of your nervous system.",
        "Some animals have four or more cone types and can see wavelengths invisible to us.",
        "Furthermore, a few people inherit a fourth cone as well.",
        "Nevertheless, we have no way to know whether what they see resembles anything we could imagine.",
      ]],
    ]},
    { title: "Reading History", weeks: [
      ["The Dust Bowl", ["erosion", "drought", "migration", "agriculture", "devastating"], ["although", "whereas", "consequently", "nevertheless", "furthermore"], [
        "The Dust Bowl of the 1930s was a natural disaster that people helped build.",
        "The southern plains had always been dry and windy, held together by deep-rooted prairie grass.",
        "During the First World War wheat prices rose sharply, and farmers plowed millions of acres of that grass under.",
        "For a decade the rains were generous and the crops were enormous.",
        "Then, in 1931, the rain stopped.",
        "With no roots to hold it, the topsoil simply lifted into the air.",
        "Storms carried dust as far as ships in the Atlantic Ocean.",
        "On a single day in April 1935, remembered as Black Sunday, visibility fell to a few feet.",
        "Consequently, hundreds of thousands of families abandoned their farms and moved west.",
        "The federal government responded by planting two hundred million trees as windbreaks and teaching contour plowing.",
        "Furthermore, the Soil Conservation Service created in 1935 still exists today.",
        "The lesson was expensive, and it was learned.",
      ]],
      ["The Underground Railroad", ["abolitionist", "conductor", "fugitive", "perilous", "network"], ["although", "whereas", "consequently", "nevertheless", "furthermore"], [
        "The Underground Railroad was neither underground nor a railroad.",
        "It was a loose network of people, routes and hiding places that helped enslaved people reach freedom.",
        "The railroad vocabulary was deliberate: safe houses were stations and guides were conductors.",
        "Because secrecy was essential, almost nothing was written down.",
        "Consequently, historians still argue about how many people escaped this way.",
        "Estimates range from thirty thousand to one hundred thousand over several decades.",
        "Harriet Tubman is the best known conductor, and she returned to the South roughly thirteen times.",
        "She later said she never lost a passenger.",
        "The work was perilous for everyone involved.",
        "After the Fugitive Slave Act of 1850, even helping someone in a free state became a federal crime.",
        "Furthermore, many escapes continued all the way to Canada because no part of the United States was safe.",
        "The courage required is difficult to overstate.",
      ]],
      ["The space race", ["satellite", "orbit", "cosmonaut", "milestone", "ambitious"], ["although", "whereas", "consequently", "nevertheless", "furthermore"], [
        "On October 4, 1957, the Soviet Union launched a metal sphere the size of a beach ball into orbit.",
        "Sputnik carried nothing but a radio transmitter and a battery.",
        "Its beeping could be picked up by amateur radio operators anywhere on Earth.",
        "The American reaction was closer to panic than curiosity.",
        "If a rocket could place a satellite over New York, it could place something else there too.",
        "Congress responded by founding NASA within a year and pouring money into science education.",
        "The Soviets reached each early milestone first: the first animal, the first man, the first woman in orbit.",
        "Yuri Gagarin completed a single orbit in April 1961.",
        "Consequently, President Kennedy chose a goal far enough away that the United States might still win it.",
        "Landing a human on the Moon was absurdly ambitious in 1961.",
        "Nevertheless, it happened eight years later, with computers less powerful than a modern calculator.",
        "Roughly four hundred thousand people worked on the program.",
      ]],
    ]},
    { title: "Reading Critically", weeks: [
      ["Evaluating sources", ["credibility", "bias", "citation", "corroborate", "scrutiny"], ["although", "whereas", "consequently", "nevertheless", "furthermore"], [
        "Anyone can publish anything, which makes evaluating sources a survival skill.",
        "Credibility is not about whether writing sounds confident.",
        "Confident writing is easy to produce and tells you nothing about accuracy.",
        "Instead, look for citations: does the author say where the information came from?",
        "A source that cannot be checked cannot be trusted, however reasonable it sounds.",
        "Bias is not the same thing as dishonesty.",
        "Every writer has a perspective, and knowing what it is helps you read them accurately.",
        "The question is not whether a source is biased but whether it is still useful once you account for the bias.",
        "Corroboration is the strongest tool you have.",
        "Two independent sources reporting the same fact is far stronger evidence than one source stating it emphatically.",
        "Furthermore, be especially skeptical of claims you already want to believe.",
        "Those are the ones that slip past your scrutiny.",
      ]],
      ["Statistics in the news", ["correlation", "causation", "sample", "average", "misleading"], ["although", "whereas", "consequently", "nevertheless", "furthermore"], [
        "Numbers in a headline feel objective, but they can mislead without containing a single falsehood.",
        "The most common error is confusing correlation with causation.",
        "Ice cream sales and drowning deaths rise together every summer.",
        "Ice cream does not cause drowning; hot weather causes both.",
        "A second problem is the sample.",
        "A survey of a thousand people can describe a nation accurately, but only if those thousand were chosen properly.",
        "A poll of people who chose to respond describes people who like answering polls.",
        "The word average hides a third trap.",
        "If nine people earn thirty thousand dollars and one earns ten million, the average income is over a million.",
        "Consequently, the median is often more honest than the mean.",
        "Furthermore, a percentage with no base number is nearly meaningless.",
        "A hundred percent increase sounds alarming until you learn it went from one case to two.",
      ]],
      ["Reading for a lifetime", ["sustained", "comprehension", "deliberate", "transferable", "cumulative"], ["although", "whereas", "consequently", "nevertheless", "furthermore"], [
        "The research on reading points to something slightly unglamorous.",
        "The strongest predictor of how well someone reads at eighteen is how much they read between eight and twelve.",
        "Not which books, and not how difficult: how much.",
        "Vocabulary growth is cumulative and quiet.",
        "A child who reads twenty minutes a day encounters roughly 1.8 million words a year.",
        "A child who reads one minute a day encounters about eight thousand.",
        "After six years that gap is unbridgeable by instruction alone.",
        "This is why fluency work matters so much early on.",
        "Reading that feels effortful does not get done voluntarily, and reading that is not voluntary stays small.",
        "Consequently, the three timed reads you have been doing are not really about speed.",
        "They are about making reading cheap enough that you will choose to do it.",
        "Nevertheless, the choosing is still yours, and it always will be.",
      ]],
    ]},
  ],
};
