import type { FluencyStage } from "./types";

/** Stages 5–8: vowel teams → r-controlled → diphthongs → advanced patterns. */
export const STAGES_5_8: FluencyStage[] = [
  {
    title: "Vowel Teams",
    emoji: "👯",
    color: "#10b981",
    soft: "#ecfdf5",
    rows: [
      ["The Rain", "ai ay", "two letters, one long a", ["rain", "train", "play", "day", "way"], [
        "It rained all day.", "I could not play outside.", "So I played with my train.",
        "The train ran all the way down the hall.", "Then the rain went away!",
        "I ran out to play.", "The rain had made a big puddle.",
        "That was the best way to end the day.",
      ]],
      ["The Green Tree", "ee", "two e's say long e", ["green", "tree", "seed", "sleep", "feet"], [
        "I planted a seed.", "I kept it in the sun.", "Soon I could see a green shoot!",
        "Week after week it grew.", "Now it is a tree.",
        "I sleep with the window open so I can see it.", "Its leaves are deep green.",
        "I keep my feet in its shade.", "That seed made a whole tree.",
      ]],
      ["The Beach", "ea", "e-a says long e", ["beach", "each", "teach", "dream", "clean"], [
        "We went to the beach.", "Each of us had a pail.",
        "Dad said he would teach me to swim.", "The sea was clean and clear.",
        "I could reach the sand bar!", "We ate a peach each.",
        "That beach day was like a dream.", "I dream of the beach each week.",
      ]],
      ["The Boat", "oa ow", "two ways to say long o", ["boat", "coat", "road", "slow", "grow"], [
        "We took a boat down the river.", "I wore my coat.", "The boat went slow.",
        "On the road beside us, cars went fast.", "But slow is fine in a boat.",
        "We saw oak trees grow along the bank.", "A goat stood on the road!",
        "We rowed the boat home.",
      ]],
      ["The Night Light", "igh ie", "two ways to say long i", ["night", "light", "right", "pie", "tie"], [
        "At night I keep a light on.", "It is on the right side of my bed.",
        "Last night I could not sleep.", "Mom made a slice of pie.",
        "She tied her robe with a tie.", "We sat in the soft light.",
        "It felt just right.", "Then I slept all night.",
      ]],
      ["The Moon", "oo", "the long /oo/ sound", ["moon", "soon", "food", "pool", "room"], [
        "The moon is bright tonight.", "Soon it will be full.",
        "I sat by the pool in my room.", "The moon made the pool glow.",
        "Mom brought food out on a tray.", "We ate by the light of the moon.",
        "Soon it will be too cool to sit outside.", "But not tonight.",
      ]],
      ["The Good Book", "oo", "the short /oo/ sound", ["book", "look", "good", "foot", "wood"], [
        "I took a good book off the shelf.", "I sat by the wood stove.",
        "I shook off my boot.", "My foot was cold!", "Look at this book, I said.",
        "It is so good I could not put it down.", "I stood up to look for another one.",
        "A good book is worth the look.",
      ]],
      ["The Blue Crew", "ue ew", "two ways to say /oo/", ["blue", "true", "crew", "new", "grew"], [
        "Our crew wore blue.", "We were a new crew.", "Each week we grew.",
        "It is true, said our coach.", "This crew is the best I knew.",
        "We flew down the river in our blue boat.", "The crowd knew our name.",
        "A new crew in blue, and it is all true!",
      ]],
      ["Fresh Bread", "ea", "when e-a says short e", ["bread", "head", "ready", "heavy", "weather"], [
        "Mom made fresh bread.", "The loaf was heavy.", "I held it over my head.",
        "Is it ready? I said.", "Not yet, said Mom.",
        "The weather was cold and wet.", "Warm bread was just what we needed.",
        "I spread butter on my slice.", "Fresh bread in bad weather is the best.",
      ]],
      ["A Day at the Sea", "mixed", "vowel team celebration", ["sea", "sail", "float", "sweet", "green"], [
        "We spent the day at the sea.", "Our boat had a white sail.",
        "We let it float on the green water.", "The breeze was sweet.",
        "I could see deep down to the sand.", "A seal came near to greet us!",
        "We ate peaches and sweet bread.", "Then we sailed home at night.",
        "What a sweet day at the sea.",
      ]],
    ],
  },
  {
    title: "Bossy R",
    emoji: "🅁",
    color: "#f43f5e",
    soft: "#fff1f2",
    rows: [
      ["The Farm", "ar", "when r bosses the a", ["farm", "barn", "car", "star", "yard"], [
        "We drove the car out to the farm.", "The barn was large and dark red.",
        "In the yard a dog barked at us.", "Grandma met us at the gate.",
        "We fed the pigs in the barn.", "After dark we sat in the yard.",
        "We counted every star we could find.", "A farm is far from town, but I love it there.",
      ]],
      ["The Shark", "ar", "more bossy ar", ["shark", "dark", "park", "sharp", "hard"], [
        "We went to the sea park.", "A shark swam past the glass.",
        "Its teeth looked sharp.", "It was hard to look away!",
        "The water was dark.", "The shark turned and swam back.",
        "Do not be scared, said the guard.", "A shark is just a large fish.",
        "I watched that shark for a long time.",
      ]],
      ["The Storm", "or", "when r bosses the o", ["storm", "corn", "horse", "short", "north"], [
        "A storm came in from the north.", "The corn bent low in the field.",
        "Our horse ran for the barn.", "It was a short storm, but a hard one.",
        "Thunder rolled across the yard.", "Then the sun came back out.",
        "The corn stood up again.", "The horse came out to eat.",
        "A storm never lasts for long.",
      ]],
      ["The Store", "ore", "o-r-e at the end", ["store", "more", "score", "before", "shore"], [
        "We walked to the store before noon.", "I had four dollars to spend.",
        "I wanted more than I could buy!", "The store sits near the shore.",
        "After, we sat and watched the water.", "A bird dove for a fish and missed.",
        "Score one for the fish, said Dad.", "We had never been to that shore before.",
        "Now we go there more and more.",
      ]],
      ["The Farmer", "er", "the /er/ sound", ["farmer", "her", "under", "water", "winter"], [
        "The farmer checked her fields.", "Winter was coming.",
        "She gave water to every animal.", "Under the barn a cat had kittens.",
        "The farmer carried them inside where it was warmer.",
        "Her hands were cold but she never stopped.",
        "In winter a farmer works harder, not less.",
        "By supper every animal was fed and warm.",
      ]],
      ["The Bird", "ir", "i with bossy r", ["bird", "girl", "first", "third", "dirt"], [
        "A girl found a bird in the dirt.", "It was her first time holding one.",
        "The bird had hurt its wing.", "She was the third person to try to help.",
        "She made a nest from a shirt.", "Day after day the bird grew stronger.",
        "Then one morning it flew!", "The girl stood in the dirt and watched it circle.",
        "Her first bird, and her best.",
      ]],
      ["The Turtle", "ur", "u with bossy r", ["turtle", "turn", "hurt", "purple", "burn"], [
        "A turtle crossed our road.", "We had to turn the car.",
        "Its shell had a purple shine in the sun.", "The road would burn its feet.",
        "I did not want it to get hurt.", "So I carried it to the grass.",
        "It took its turn and walked away slowly.",
        "A turtle is never in a hurry.", "I think that turtle thanked me.",
      ]],
      ["The Chair", "air are", "the /air/ sound", ["chair", "hair", "pair", "share", "care"], [
        "Grandpa has an old chair.", "He sits there to brush his hair.",
        "He keeps a pair of glasses on the arm.", "He takes care of that chair.",
        "He says it is older than my dad!", "Sometimes we share it.",
        "I sit on one arm and he sits in the seat.",
        "That pair — Grandpa and his chair — belong together.",
      ]],
      ["This Year", "ear", "the /ear/ sound", ["year", "hear", "near", "clear", "dear"], [
        "This year I grew two inches!", "I can hear better than my dear old dog.",
        "He cannot hear me near the door.", "So I clap, and he comes.",
        "The air was clear this year.", "We spent nearly every day outside.",
        "I will remember this year.", "Next year I will be even taller.",
        "Each year goes by so fast.",
      ]],
      ["The Park", "mixed", "bossy r celebration", ["park", "garden", "corner", "sister", "bird"], [
        "My sister and I walked to the park.", "There is a garden on the corner.",
        "A bird sang from the tall fir tree.", "We sat on the warm grass.",
        "A farmer sold corn from a cart.", "We shared a short walk by the water.",
        "The sun turned the whole garden gold.", "My sister said it was her best day this year.",
        "I think that park is perfect.",
      ]],
    ],
  },
  {
    title: "Tricky Vowels",
    emoji: "🌀",
    color: "#a855f7",
    soft: "#faf5ff",
    rows: [
      ["The Loud Mouse", "ou", "the /ow/ sound", ["loud", "mouse", "house", "found", "around"], [
        "There was a loud sound in our house.", "We found a mouse!",
        "It ran around and around the counter.", "Mom shouted and climbed on a chair.",
        "Dad counted to three and dropped a cup over it.",
        "We carried the mouse outside without hurting it.",
        "It ran south toward the field.", "Our house was quiet again.",
        "But I still hear sounds at night.",
      ]],
      ["The Brown Owl", "ow", "when ow says /ow/", ["brown", "owl", "down", "town", "now"], [
        "A brown owl lives near our town.", "It comes out when the sun goes down.",
        "Now and then I hear it from my window.", "Last night it flew down to our fence.",
        "It did not make a sound!", "Its brown feathers blended with the bark.",
        "I counted to ten, and then it was gone.",
        "An owl can fly without a sound.", "That is how it hunts.",
      ]],
      ["The Coin", "oi", "the /oy/ sound", ["coin", "join", "point", "soil", "boil"], [
        "I found an old coin in the soil.", "It was dark green from the rain.",
        "Dad said we could boil water and clean it.", "There was a point of light on one side.",
        "It turned out to be a date!", "Will you join me in the garden? I asked.",
        "We dug all afternoon.", "We found two more coins in the soil.",
        "That coin was the best thing I ever found.",
      ]],
      ["The Boy's Toy", "oy", "oy at the end", ["boy", "toy", "joy", "enjoy", "royal"], [
        "A boy got a toy for his birthday.", "It was a royal blue truck.",
        "He could not hide his joy.", "He played with that toy every day.",
        "He let his sister enjoy it too.", "They would destroy a whole pile of blocks with it!",
        "The joy of a good toy never gets old.",
        "That boy still has it on his shelf.",
      ]],
      ["The Hawk", "au aw", "two ways to say /aw/", ["hawk", "claw", "draw", "because", "autumn"], [
        "In autumn a hawk sits on our fence.", "I like to draw it.",
        "Its claws grip the wood hard.", "I drew its beak and its tail.",
        "I paused because it turned its head.", "It saw me through the glass!",
        "Then it launched off the fence.", "I kept drawing from memory.",
        "That autumn hawk became my best drawing.",
      ]],
      ["The Tall Wall", "all alk", "all and alk", ["tall", "wall", "small", "walk", "talk"], [
        "There is a tall wall behind our school.", "I walk past it every morning.",
        "A small door sits in the middle.", "We all talk about what is behind it.",
        "Last fall I finally asked.", "It is just a garden, said the caretaker.",
        "He let us all walk through.", "It was small, but it had an apple tree.",
        "Now we talk about the apples instead.",
      ]],
      ["I Caught It", "augh ough", "tricky spellings for /aw/", ["caught", "taught", "thought", "bought", "brought"], [
        "My grandpa taught me to fish.", "I thought it would be easy.",
        "For an hour I caught nothing at all.", "Then my line pulled hard!",
        "I caught a trout bigger than my arm.", "Grandpa brought the net over fast.",
        "We bought ice on the way home to keep it cold.",
        "I thought about that fish all week.",
        "Grandpa taught me well.",
      ]],
      ["The Shy Fly", "y", "when y says long i", ["shy", "fly", "try", "sky", "why"], [
        "A shy fly sat on my window.", "I wondered why it would not fly.",
        "The sky outside was dry and bright.", "I tried to shoo it with a cloth.",
        "It would not budge.", "So I tried opening the window instead.",
        "It flew out into the sky!", "Sometimes you just have to try another way.",
        "Why fight it? I thought.",
      ]],
      ["The Happy Puppy", "y", "when y says long e", ["puppy", "happy", "funny", "sunny", "candy"], [
        "We got a puppy on a sunny day.", "She is very funny.",
        "She carries my socks around the family room.",
        "Every body in the family is happy.", "She is not allowed candy, of course.",
        "But she begs anyway!", "Her belly is soft and her tail never stops.",
        "A puppy makes every day sunny.",
        "I am lucky to have such a happy, funny puppy.",
      ]],
      ["The Loud Night", "mixed", "tricky vowel celebration", ["sound", "crowd", "point", "small", "July"], [
        "On the fourth of July a crowd fills our small town.",
        "The sound of the band carries down every street.",
        "We found a good point on the hill to watch from.",
        "At the moment the sky turned dark, the first rocket flew up.",
        "The crowd shouted all around us.", "My small brother covered his ears.",
        "The loud booms bounced off the brown hills.",
        "We walked home by the light of the moon.",
        "July nights are the best nights.",
      ]],
    ],
  },
  {
    title: "Big Words",
    emoji: "🏔️",
    color: "#0891b2",
    soft: "#ecfeff",
    rows: [
      ["The Ice Dance", "c", "when c says /s/", ["ice", "nice", "dance", "city", "circle"], [
        "In the center of the city there is an ice rink.",
        "Once a year they hold a dance on the ice.",
        "The skaters circle round and round.", "Their faces are nice to watch.",
        "A girl in a silver dress raced past us.", "She spun in a perfect circle.",
        "The crowd was silent, then cheered.",
        "I decided right then I would learn to skate.",
        "The city ice dance is my favorite night of the year.",
      ]],
      ["The Giant Gem", "g", "when g says /j/", ["giant", "gem", "magic", "page", "change"], [
        "In the story, a giant guards a gem.", "The gem is said to hold magic.",
        "On every page the hero gets closer.", "Would the giant change his mind?",
        "At the edge of the bridge they finally meet.",
        "The giant is gentle, it turns out.", "He gives the gem away.",
        "The magic was never in the gem at all.",
        "I read that page again and again.",
      ]],
      ["Catch the Badge", "tch dge", "tch and dge endings", ["catch", "match", "watch", "badge", "bridge"], [
        "There was a match on Saturday.", "I had to catch the early bus.",
        "We crossed the bridge into town.", "My coach gave me a badge to wear.",
        "I had to watch the ball the whole time.", "In the last minute I made the catch!",
        "The whole bench jumped up.", "We won the match by one point.",
        "I still have that badge on my shelf.",
      ]],
      ["The Knight", "kn wr gn", "letters that stay silent", ["knight", "knee", "know", "write", "wrong"], [
        "I know a story about a knight.", "He hurt his knee in a fight.",
        "He had to wrap it with cloth.", "People said he was wrong to keep going.",
        "But the knight did not listen.", "He wrote a letter to the king.",
        "In it he knelt, in words, and asked for one more chance.",
        "The king gave it.", "The knight won, bad knee and all.",
      ]],
      ["The Photo", "ph gh", "when letters say /f/", ["photo", "phone", "graph", "laugh", "enough"], [
        "Grandma showed me an old photo.", "It was taken before phones had cameras.",
        "In it she is young enough to be my sister!",
        "She is mid-laugh, caught by surprise.",
        "On the back is a date in her handwriting.",
        "I made a graph of our family on paper.",
        "Each photo got its own spot.", "It was tough to fit them all.",
        "That laugh in the photo is exactly her laugh now.",
      ]],
      ["The Little Turtle", "-le", "words ending in -le", ["little", "turtle", "apple", "candle", "simple"], [
        "A little turtle lives in the puddle behind our house.",
        "I gave him a piece of apple.", "He took a nibble, then another.",
        "In the middle of the garden I lit a candle.",
        "The turtle did not startle at all.",
        "He just settled into the cool soil.",
        "His life looks simple from the outside.",
        "But that little turtle has been here longer than I have.",
        "I like to think he is gentle because he is old.",
      ]],
      ["Unlock It", "un re pre dis", "prefixes at the front", ["unlock", "redo", "unhappy", "preview", "disagree"], [
        "The door would not unlock.", "I had to redo the whole thing.",
        "My brother was unhappy about the wait.", "We began to disagree about the key.",
        "Then I remembered the preview on my phone.",
        "There was a photo of where the spare was hidden!",
        "I had to unbury it from under a rock.",
        "The door unlocked on the first try.",
        "A prefix changes a word, and that one changed our whole day.",
      ]],
      ["The Fastest Runner", "-ing -ed -er -est", "endings that change a word", ["fastest", "running", "jumped", "helpful", "careless"], [
        "My sister is the fastest runner in her grade.",
        "She has been running since she was six.",
        "Last week she jumped over a hurdle without slowing down.",
        "Her coach is helpful and never careless with her training.",
        "She is quicker than she was last year, and stronger too.",
        "At the biggest meet of the season she finished first.",
        "She was smiling and crying at the same time.",
        "Being the fastest took years of working.",
        "Nothing about it was effortless.",
      ]],
      ["The Adventure", "multisyllable", "long words, chunk by chunk", ["adventure", "fantastic", "important", "remember", "wonderful"], [
        "Last summer we went on a fantastic adventure.",
        "We traveled to the mountains for a week.",
        "The most important thing, Dad said, was to remember to look up.",
        "So we did.", "The wonderful thing about mountains is how quiet they are.",
        "We discovered a waterfall nobody had mentioned.",
        "I will remember the temperature of that water forever.",
        "Adventures are better when they are unexpected.",
        "I understand now why Dad wanted us to look up.",
      ]],
      ["The Whole Story", "all patterns", "you can read anything now", ["whole", "journey", "together", "finally", "celebrate"], [
        "This is the last story in the whole book.",
        "Think about where you started.",
        "The first story was about a cat on a mat.",
        "Now you are reading sentences with words like journey and celebrate.",
        "That did not happen by accident.",
        "It happened because you read, and read again, and read a third time.",
        "You got faster because you kept going.",
        "Finally, you finished the whole journey.",
        "Let's celebrate together — you are a reader.",
      ]],
    ],
  },
];
